"""Canonical generated-file header shared by renderers and synchronization."""

GENERATED_HEADER_PREFIX = "# GENERATED by generate-quadlets.py from quadlets/"
GENERATED_HEADER_SUFFIX = " — DO NOT EDIT"


def generated_header(source: str) -> str:
    return f"{GENERATED_HEADER_PREFIX}{source}{GENERATED_HEADER_SUFFIX}"
