#!/usr/bin/env python3
# ABOUTME: Generates the rootless-service boilerplate (container quadlets,
# sysusers.d, tmpfiles.d, ensure-account scripts/units, subuid/subgid) into
# overlay-root/ from the declarative configs in quadlets/*.toml.

import re
import sys
import textwrap
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent
QUADLET_DIR = REPO / "quadlets"
OVERLAY = REPO / "overlay-root"
SOPS_FILE = OVERLAY / "usr/share/custom-coreos/secrets/secrets.sops.yaml"
SUBID_COUNT = 65536
GENERATED_HEADER_PREFIX = "# GENERATED by generate-quadlets.py from quadlets/"
GENERATED_HEADER_SUFFIX = " — DO NOT EDIT"

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
USERNAME_RE = re.compile(r"^_nas_[a-z0-9]+$")


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def header(toml_path: Path) -> str:
    return f"{GENERATED_HEADER_PREFIX}{toml_path.name}{GENERATED_HEADER_SUFFIX}"


def wrap_comment(text: str) -> str:
    return textwrap.fill(text, width=78, initial_indent="# ", subsequent_indent="# ")


def load_service(toml_path: Path) -> dict:
    with open(toml_path, "rb") as f:
        cfg = tomllib.load(f)

    for section in ("service", "host", "container"):
        if section not in cfg:
            die(f"{toml_path.name}: missing required [{section}] section")

    svc, host, container = cfg["service"], cfg["host"], cfg["container"]
    for key in ("name", "description"):
        if key not in svc:
            die(f"{toml_path.name}: missing [service].{key}")
    for key in ("username", "uid", "subid-start", "display-name"):
        if key not in host:
            die(f"{toml_path.name}: missing [host].{key}")
    if "image" not in container:
        die(f"{toml_path.name}: missing [container].image")

    if not NAME_RE.match(svc["name"]):
        die(f"{toml_path.name}: [service].name must match {NAME_RE.pattern}")
    if not USERNAME_RE.match(host["username"]):
        die(f"{toml_path.name}: [host].username must match {USERNAME_RE.pattern}")
    cfg["_toml_path"] = toml_path
    cfg["_slug"] = host["username"].removeprefix("_nas_")
    return cfg


def validate_fleet(configs: list[dict]) -> None:
    seen: dict[str, tuple] = {}
    ranges: list[tuple[int, int, str]] = []
    for cfg in configs:
        name = cfg["_toml_path"].name
        for key, value in (
            ("service name", cfg["service"]["name"]),
            ("username", cfg["host"]["username"]),
            ("uid", cfg["host"]["uid"]),
        ):
            if (key, value) in seen:
                die(f"{name}: duplicate {key} {value!r} (also in {seen[(key, value)]})")
            seen[(key, value)] = name
        start = cfg["host"]["subid-start"]
        ranges.append((start, start + SUBID_COUNT, name))
    ranges.sort()
    for (_, prev_end, prev_name), (cur_start, _, cur_name) in zip(ranges, ranges[1:]):
        if cur_start < prev_end:
            die(f"subordinate ID ranges overlap between {prev_name} and {cur_name}")


def sops_secret_keys() -> set[str]:
    # SOPS leaves top-level YAML key names in the clear; the only structural
    # key it adds is its own "sops" metadata block.
    keys = set()
    for line in SOPS_FILE.read_text().splitlines():
        m = re.match(r"^([A-Za-z0-9_-]+):", line)
        if m:
            keys.add(m.group(1))
    keys.discard("sops")
    return keys


def verify_sops(configs: list[dict]) -> None:
    declared = {
        (cfg["_toml_path"].name, secret["name"])
        for cfg in configs
        for secret in cfg["container"].get("secrets", [])
    }
    if not declared:
        return
    if not SOPS_FILE.exists():
        die(f"secrets are declared but {SOPS_FILE} does not exist")
    available = sops_secret_keys()
    missing = [(toml, name) for toml, name in sorted(declared) if name not in available]
    if missing:
        for toml, name in missing:
            print(f"ERROR: {toml}: secret {name!r} not found in {SOPS_FILE.name}", file=sys.stderr)
        sys.exit(1)


def container_unit(cfg: dict) -> str:
    svc, host, container = cfg["service"], cfg["host"], cfg["container"]
    unit = cfg.get("unit", {})
    extra = unit.get("extra", {})
    secrets = container.get("secrets", [])

    lines = [header(cfg["_toml_path"])]
    lines += ["[Unit]", f"Description={svc['description']}"]
    if "documentation" in svc:
        lines.append(f"Documentation={svc['documentation']}")
    lines += extra.get("Unit", [])

    lines += ["", "[Container]"]
    lines.append(f"ContainerName={svc['name']}")
    lines.append(f"Image={container['image']}")
    if "network" in container:
        lines.append(f"Network={container['network']}")
    if "auto-update" in container:
        lines.append(f"AutoUpdate={container['auto-update']}")
    if "container-user" in container:
        lines.append(f"User={container['container-user']}")

    environment = container.get("environment", {})
    if environment:
        lines.append("")
        lines += [f"Environment={k}={v}" for k, v in environment.items()]

    for volume in container.get("volumes", []):
        lines.append("")
        if "comment" in volume:
            lines.append(f"# {volume['comment']}")
        options = f":{volume['options']}" if volume.get("options") else ""
        lines.append(f"Volume={volume['source']}:{volume['target']}{options}")

    for secret in secrets:
        target = secret.get("target", f"/run/secrets/{secret['name']}")
        lines.append("")
        lines.append("# Runtime secret written at boot by sops-distribute-secrets.service")
        lines.append(f"Volume=/run/nas-secrets/{svc['name']}/{secret['name']}:{target}:ro,Z")

    if "exec" in container:
        lines += ["", f"Exec={container['exec']}"]

    lines += ["", f"Pull={container.get('pull', 'newer')}"]
    lines += extra.get("Container", [])

    lines += ["", "[Service]"]
    lines += [
        f"ExecStartPre=/usr/bin/test -r /run/nas-secrets/{svc['name']}/{secret['name']}"
        for secret in secrets
    ]
    lines += extra.get("Service", [])
    lines.append("Restart=always")
    lines.append(f"RestartSec={unit.get('restart-sec', 30)}")
    if "timeout-start-sec" in unit:
        lines.append(f"TimeoutStartSec={unit['timeout-start-sec']}")

    lines += ["", "[Install]", "WantedBy=default.target"]
    lines += extra.get("Install", [])
    return "\n".join(lines) + "\n"


def sysusers_conf(cfg: dict) -> str:
    host = cfg["host"]
    user, uid, display = host["username"], host["uid"], host["display-name"]
    comment = wrap_comment(
        f"Host account for the rootless {display} Quadlet. This must stay usable by "
        'systemd\'s lingering user manager, so do not mark it as a fully locked "u!" '
        "account."
    )
    return "\n".join(
        [
            header(cfg["_toml_path"]),
            comment,
            f"g {user} {uid}",
            f'u {user} {uid}:{uid} "NAS {display} service user" /var/home/{user} /sbin/nologin',
        ]
    ) + "\n"


def tmpfiles_conf(cfg: dict) -> str:
    host = cfg["host"]
    user, display = host["username"], host["display-name"]
    lines = [
        header(cfg["_toml_path"]),
        wrap_comment(
            f"Rootless {display} uses a namespaced host account so the service identity "
            "does not collide with upstream image defaults."
        ),
    ]
    if "data" in cfg:
        path = cfg["data"]["path"]
        mode = cfg["data"].get("mode", "0750")
        lines.append(f"d {path} {mode} {user} {user} -")
        lines.append(f"Z {path} {mode} {user} {user} -")
    home = f"/var/home/{user}"
    for subdir in ("", "/.config", "/.config/containers", "/.local", "/.local/share",
                   "/.local/share/containers", "/.cache"):
        lines.append(f"d {home}{subdir} 0750 {user} {user} -")
    lines.append("d /var/lib/systemd/linger 0755 root root -")
    lines.append(f"f /var/lib/systemd/linger/{user} 0644 root root -")
    return "\n".join(lines) + "\n"


def ensure_account_script(cfg: dict) -> str:
    host = cfg["host"]
    user, uid = host["username"], host["uid"]

    fcontext_vars = []
    fcontext_calls = []
    if "assets" in cfg:
        fcontext_vars.append(f'ASSETS_FCONTEXT="{cfg["assets"]["path"]}(/.*)?"')
        fcontext_calls.append('ensure_fcontext_rule "${ASSETS_FCONTEXT}"')
    if "data" in cfg:
        fcontext_vars.append(f'DATA_FCONTEXT="{cfg["data"]["path"]}(/.*)?"')
        fcontext_calls.append('ensure_fcontext_rule "${DATA_FCONTEXT}"')

    data_block = ""
    if "data" in cfg:
        data_path = cfg["data"]["path"]
        data_block = f"""
if [[ -e {data_path} ]]; then
    log "Restoring SELinux labels for {data_path}"
    restorecon -F -R {data_path}
fi
"""

    fcontext_var_lines = ("\n" + "\n".join(fcontext_vars)) if fcontext_vars else ""
    fcontext_call_lines = ("\n".join(fcontext_calls) + "\n") if fcontext_calls else ""

    return f"""#!/bin/bash
{header(cfg["_toml_path"])}
# ABOUTME: Ensures the {user} rootless service account has the state
# required for a lingering user manager.

set -euo pipefail

USER_NAME="{user}"
USER_UID="{uid}"
USER_HOME="/var/home/{user}"
USER_SHELL="/sbin/nologin"
USER_SUBID_START="{host["subid-start"]}"
USER_SUBID_COUNT="{SUBID_COUNT}"{fcontext_var_lines}

log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}}

ensure_subid_entry() {{
    local file="$1"
    local expected="${{USER_NAME}}:${{USER_SUBID_START}}:${{USER_SUBID_COUNT}}"
    local current

    if [[ ! -e "${{file}}" ]]; then
        install -o root -g root -m 0644 /dev/null "${{file}}"
    fi

    current="$(grep -E "^${{USER_NAME}}:" "${{file}}" || true)"

    if [[ -z "${{current}}" ]]; then
        log "Adding ${{expected}} to ${{file}}"
        printf '%s\\n' "${{expected}}" >> "${{file}}"
        return
    fi

    if [[ "${{current}}" != "${{expected}}" ]]; then
        log "Leaving existing ${{file}} entry for ${{USER_NAME}}: ${{current}}"
    fi
}}

ensure_fcontext_rule() {{
    local target="$1"

    if semanage fcontext -a -t container_file_t -r s0 "${{target}}" 2>/dev/null; then
        log "Added SELinux fcontext for ${{target}}"
        return
    fi

    semanage fcontext -m -t container_file_t -r s0 "${{target}}"
}}

if ! getent passwd "${{USER_NAME}}" >/dev/null; then
    log "User ${{USER_NAME}} does not exist yet, skipping"
    exit 0
fi

shadow_entry="$(getent shadow "${{USER_NAME}}" || true)"
shadow_password_field="${{shadow_entry#*:}}"
shadow_password_field="${{shadow_password_field%%:*}}"

if [[ -z "${{shadow_password_field}}" || "${{shadow_password_field}}" == "!"* ]]; then
    log "Resetting ${{USER_NAME}} to an invalid but not fully locked password marker"
    usermod --password '*' "${{USER_NAME}}"
fi

log "Clearing account expiry for ${{USER_NAME}}"
chage --expiredate -1 "${{USER_NAME}}"

current_home="$(getent passwd "${{USER_NAME}}" | cut -d: -f6)"
if [[ "${{current_home}}" != "${{USER_HOME}}" ]]; then
    log "Resetting home for ${{USER_NAME}} to ${{USER_HOME}}"
    usermod --home "${{USER_HOME}}" "${{USER_NAME}}"
fi

current_shell="$(getent passwd "${{USER_NAME}}" | cut -d: -f7)"
if [[ "${{current_shell}}" != "${{USER_SHELL}}" ]]; then
    log "Resetting shell for ${{USER_NAME}} to ${{USER_SHELL}}"
    usermod --shell "${{USER_SHELL}}" "${{USER_NAME}}"
fi

ensure_subid_entry /etc/subuid
ensure_subid_entry /etc/subgid
{fcontext_call_lines}{data_block}
if systemctl is-failed --quiet "user@${{USER_UID}}.service"; then
    log "Retrying user@${{USER_UID}}.service after account setup"
    systemctl reset-failed "user@${{USER_UID}}.service"
    systemctl start "user@${{USER_UID}}.service"
fi
"""


def ensure_account_unit(cfg: dict) -> str:
    host = cfg["host"]
    user, uid, slug = host["username"], host["uid"], cfg["_slug"]
    return f"""{header(cfg["_toml_path"])}
[Unit]
Description=Prepare {user} for a lingering user manager
DefaultDependencies=no
After=local-fs.target systemd-sysusers.service systemd-tmpfiles-setup.service
Before=sysinit.target systemd-logind.service user@{uid}.service
ConditionPathExists=/etc/passwd

[Service]
Type=oneshot
ExecStart=/usr/local/bin/ensure-nas-{slug}-account.sh
RemainAfterExit=yes

[Install]
WantedBy=sysinit.target
"""


def subid_file(configs: list[dict]) -> str:
    # No header comment: shadow-utils does not document comment support in
    # subuid/subgid, so these files stay bare.
    return "".join(
        f"{cfg['host']['username']}:{cfg['host']['subid-start']}:{SUBID_COUNT}\n"
        for cfg in configs
    )


def write(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    changed = not path.exists() or path.read_text() != content
    if changed:
        path.write_text(content)
    if executable:
        path.chmod(0o755)
    print(f"{'wrote' if changed else 'ok   '} {path.relative_to(REPO)}")


def generated_paths(cfg: dict) -> set[Path]:
    uid, slug, name = cfg["host"]["uid"], cfg["_slug"], cfg["service"]["name"]
    return {
        OVERLAY / f"etc/containers/systemd/users/{uid}/{name}.container",
        OVERLAY / f"usr/lib/sysusers.d/nas-{slug}.conf",
        OVERLAY / f"usr/lib/tmpfiles.d/nas-{slug}-rootless.conf",
        OVERLAY / f"usr/local/bin/ensure-nas-{slug}-account.sh",
        OVERLAY / f"etc/systemd/system/ensure-nas-{slug}-account.service",
    }


def has_generated_header(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    try:
        with path.open(errors="replace") as generated_file:
            for _ in range(2):
                line = generated_file.readline().rstrip("\n")
                if line.startswith(GENERATED_HEADER_PREFIX) and line.endswith(
                    GENERATED_HEADER_SUFFIX
                ):
                    return True
    except OSError:
        return False
    return False


def remove_stale_generated(expected_paths: set[Path], overlay: Path = OVERLAY) -> None:
    stale_paths = sorted(
        path
        for path in overlay.rglob("*")
        if path not in expected_paths and has_generated_header(path)
    )
    for path in stale_paths:
        path.unlink()
        print(f"removed {path.relative_to(REPO)}")

        # Per-UID Quadlet directories are generator-created. Other output
        # directories are shared with hand-written overlay files.
        users_dir = overlay / "etc/containers/systemd/users"
        if path.parent.parent == users_dir:
            try:
                path.parent.rmdir()
            except OSError:
                pass


def main() -> None:
    toml_paths = sorted(QUADLET_DIR.glob("*.toml"))
    if not toml_paths:
        die(f"no TOML configs found in {QUADLET_DIR}")

    configs = sorted((load_service(p) for p in toml_paths), key=lambda c: c["host"]["uid"])
    validate_fleet(configs)
    verify_sops(configs)

    expected_paths = set()
    for cfg in configs:
        uid, slug, name = cfg["host"]["uid"], cfg["_slug"], cfg["service"]["name"]
        expected_paths.update(generated_paths(cfg))
        write(
            OVERLAY / f"etc/containers/systemd/users/{uid}/{name}.container",
            container_unit(cfg),
        )
        write(OVERLAY / f"usr/lib/sysusers.d/nas-{slug}.conf", sysusers_conf(cfg))
        write(OVERLAY / f"usr/lib/tmpfiles.d/nas-{slug}-rootless.conf", tmpfiles_conf(cfg))
        write(
            OVERLAY / f"usr/local/bin/ensure-nas-{slug}-account.sh",
            ensure_account_script(cfg),
            executable=True,
        )
        write(
            OVERLAY / f"etc/systemd/system/ensure-nas-{slug}-account.service",
            ensure_account_unit(cfg),
        )

    write(OVERLAY / "etc/subuid", subid_file(configs))
    write(OVERLAY / "etc/subgid", subid_file(configs))
    remove_stale_generated(expected_paths)


if __name__ == "__main__":
    main()
