#!/usr/bin/env python3
# ABOUTME: Generates the rootless-service boilerplate (container quadlets,
# sysusers.d, tmpfiles.d, ensure-account scripts/units, subuid/subgid) into
# overlay-root/ from the declarative configs in quadlets/*.toml.

import ipaddress
import re
import sys
import textwrap
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent
QUADLET_DIR = REPO / "quadlets"
OVERLAY = REPO / "overlay-root"
SOPS_FILE = OVERLAY / "usr/share/custom-coreos/secrets/secrets.sops.yaml"
SUBID_COUNT = 65536
GENERATED_HEADER_PREFIX = "# GENERATED by generate-quadlets.py from quadlets/"
GENERATED_HEADER_SUFFIX = " — DO NOT EDIT"

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
USERNAME_RE = re.compile(r"^_nas_[a-z0-9]+$")
PINNED_IMAGE_RE = re.compile(r"^[^@\s]+:[^@:\s]+@sha256:[0-9a-f]{64}$")
TAP_NAME_RE = re.compile(r"^krun-[0-9]{5}$")
KRUN_DNS_SERVERS = ("100.100.100.100", "75.75.75.75", "75.75.76.76")


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def header(toml_path: Path) -> str:
    return f"{GENERATED_HEADER_PREFIX}{toml_path.name}{GENERATED_HEADER_SUFFIX}"


def wrap_comment(text: str) -> str:
    return textwrap.fill(text, width=78, initial_indent="# ", subsequent_indent="# ")


def validate_ports(
    toml_name: str, container: dict, *, allow_host_network: bool = False
) -> None:
    ports = container.get("ports", [])
    if not isinstance(ports, list):
        die(f"{toml_name}: [container].ports must be an array of tables")
    if ports and container.get("network") == "host" and not allow_host_network:
        die(f"{toml_name}: [container].ports cannot be used with network = \"host\"")

    seen = set()
    for index, port in enumerate(ports, start=1):
        field = f"[container].ports[{index}]"
        if not isinstance(port, dict):
            die(f"{toml_name}: {field} must be a table")

        unknown = sorted(set(port) - {"host", "container", "protocol"})
        if unknown:
            die(f"{toml_name}: {field} has unknown keys: {', '.join(unknown)}")
        for key in ("host", "container"):
            if key not in port:
                die(f"{toml_name}: {field} is missing {key!r}")

        host = port["host"]
        if not isinstance(host, str) or not host:
            die(f"{toml_name}: {field}.host must be a non-empty string")

        if host.startswith("["):
            match = re.fullmatch(r"\[([^]]+)]:(\d+)", host)
            expected_version = 6
        else:
            match = re.fullmatch(r"([^:]+):(\d+)", host)
            expected_version = 4
        if match is None:
            die(
                f"{toml_name}: {field}.host must be an IPv4:port or "
                "[IPv6]:port endpoint"
            )

        try:
            address = ipaddress.ip_address(match.group(1))
        except ValueError:
            die(f"{toml_name}: {field}.host contains an invalid IP address")
        if address.version != expected_version:
            die(f"{toml_name}: {field}.host must bracket IPv6 addresses")

        host_port = int(match.group(2))
        if not 1 <= host_port <= 65535:
            die(f"{toml_name}: {field}.host port must be between 1 and 65535")

        container_port = port["container"]
        if type(container_port) is not int or not 1 <= container_port <= 65535:
            die(f"{toml_name}: {field}.container must be an integer from 1 to 65535")

        protocol = port.get("protocol", "tcp")
        if protocol not in {"tcp", "udp"}:
            die(f'{toml_name}: {field}.protocol must be "tcp" or "udp"')

        rendered = f"{host}:{container_port}/{protocol}"
        if rendered in seen:
            die(f"{toml_name}: duplicate published port {rendered!r}")
        seen.add(rendered)


def validate_dns(toml_name: str, container: dict) -> None:
    servers = container.get("dns", [])
    if not isinstance(servers, list):
        die(f"{toml_name}: [container].dns must be an array of IP addresses")

    seen = set()
    for index, server in enumerate(servers, start=1):
        field = f"[container].dns[{index}]"
        if not isinstance(server, str):
            die(f"{toml_name}: {field} must be an IP address string")
        try:
            address = ipaddress.ip_address(server)
        except ValueError:
            die(f"{toml_name}: {field} must be a valid IP address")
        if server in seen:
            die(f"{toml_name}: duplicate DNS server {server!r}")
        seen.add(server)


def validate_sysctls(toml_name: str, container: dict) -> None:
    sysctls = container.get("sysctls", [])
    if not isinstance(sysctls, list):
        die(f"{toml_name}: [container].sysctls must be an array of strings")

    seen = set()
    for index, setting in enumerate(sysctls, start=1):
        field = f"[container].sysctls[{index}]"
        if not isinstance(setting, str) or not re.fullmatch(
            r"[A-Za-z0-9_.-]+=[^\s=]+", setting
        ):
            die(f'{toml_name}: {field} must use "name=value" format')
        if setting in seen:
            die(f"{toml_name}: duplicate sysctl {setting!r}")
        seen.add(setting)


def validate_krun(toml_name: str, cfg: dict) -> None:
    if "krun" not in cfg:
        return

    krun = cfg["krun"]
    if not isinstance(krun, dict):
        die(f"{toml_name}: [krun] must be a table")

    unknown = sorted(
        set(krun)
        - {
            "enabled",
            "cpus",
            "ram-mib",
            "network",
            "ipv4",
            "ingress",
            "host-access",
        }
    )
    if unknown:
        die(f"{toml_name}: [krun] has unknown keys: {', '.join(unknown)}")

    if "enabled" not in krun or type(krun["enabled"]) is not bool:
        die(f"{toml_name}: [krun].enabled must be a boolean")

    if not krun["enabled"]:
        fields = sorted(set(krun) - {"enabled"})
        if fields:
            die(
                f"{toml_name}: [krun] fields are not allowed when disabled: "
                f"{', '.join(fields)}"
            )
        return

    for key in ("cpus", "ram-mib"):
        if key not in krun:
            die(f"{toml_name}: missing [krun].{key}")
        if type(krun[key]) is not int or krun[key] <= 0:
            die(f"{toml_name}: [krun].{key} must be a positive integer")

    if krun["ram-mib"] < 128:
        die(f"{toml_name}: [krun].ram-mib must be at least 128")

    network = krun.get("network", "tsi")
    if network not in {"tsi", "passt", "tap"}:
        die(f'{toml_name}: [krun].network must be "tsi", "passt", or "tap"')

    container = cfg.get("container", {})
    if network == "passt" and container.get("network") == "host":
        die(
            f'{toml_name}: [krun].network = "passt" requires a private '
            "container network namespace"
        )
    if network == "tap":
        if container.get("network") != "host":
            die(f'{toml_name}: [krun].network = "tap" requires network = "host"')
        if "ipv4" not in krun:
            die(f"{toml_name}: TAP networking requires [krun].ipv4")
        try:
            guest = ipaddress.ip_interface(krun["ipv4"])
        except (TypeError, ValueError):
            die(f"{toml_name}: [krun].ipv4 must be an IPv4 interface address")
        if guest.version != 4 or guest.network.prefixlen != 30:
            die(f"{toml_name}: [krun].ipv4 must use a dedicated IPv4 /30")
        if guest.ip != guest.network.network_address + 2:
            die(f"{toml_name}: [krun].ipv4 must be the second usable /30 address")
        for port in container.get("ports", []):
            address_text = port["host"].rsplit(":", 1)[0]
            if address_text not in {"127.0.0.1", "0.0.0.0"}:
                die(
                    f"{toml_name}: TAP host publications support only "
                    '"127.0.0.1" or "0.0.0.0" addresses'
                )

        ingress = krun.get("ingress", [])
        if not isinstance(ingress, list):
            die(f"{toml_name}: [[krun.ingress]] must be an array of tables")
        seen_ingress = set()
        for rule in ingress:
            if not isinstance(rule, dict) or set(rule) != {"from", "ports"}:
                die(f"{toml_name}: each [[krun.ingress]] needs only from and ports")
            if not isinstance(rule["from"], str) or not NAME_RE.fullmatch(rule["from"]):
                die(f"{toml_name}: [[krun.ingress]].from must be a service name")
            ports = rule["ports"]
            if not isinstance(ports, list) or not ports or any(
                type(port) is not int or not 1 <= port <= 65535 for port in ports
            ):
                die(f"{toml_name}: [[krun.ingress]].ports must contain TCP ports")
            if len(set(ports)) != len(ports):
                die(f"{toml_name}: [[krun.ingress]].ports contains duplicates")
            key = (rule["from"], tuple(ports))
            if key in seen_ingress:
                die(f"{toml_name}: duplicate [[krun.ingress]] rule")
            seen_ingress.add(key)

        host_access = krun.get("host-access", [])
        if not isinstance(host_access, list) or any(
            type(port) is not int or not 1 <= port <= 65535
            for port in host_access
        ):
            die(f"{toml_name}: [krun].host-access must be an array of TCP ports")
        if len(set(host_access)) != len(host_access):
            die(f"{toml_name}: [krun].host-access contains duplicates")
    elif set(krun) & {"ipv4", "ingress", "host-access"}:
        die(f"{toml_name}: TAP-only [krun] fields require network = \"tap\"")
    if container.get("network") == "host":
        for server in container.get("dns", []):
            if ipaddress.ip_address(server).is_loopback:
                die(
                    f"{toml_name}: krun with network = \"host\" cannot use "
                    f"loopback DNS server {server!r}"
                )


def load_service(toml_path: Path) -> dict:
    with open(toml_path, "rb") as f:
        cfg = tomllib.load(f)

    for section in ("service", "host", "container"):
        if section not in cfg:
            die(f"{toml_path.name}: missing required [{section}] section")

    svc, host, container = cfg["service"], cfg["host"], cfg["container"]
    for key in ("name", "description"):
        if key not in svc:
            die(f"{toml_path.name}: missing [service].{key}")
    for key in ("username", "uid", "subid-start", "display-name"):
        if key not in host:
            die(f"{toml_path.name}: missing [host].{key}")
    if "image" not in container:
        die(f"{toml_path.name}: missing [container].image")

    enabled = container.get("enabled", True)
    if type(enabled) is not bool:
        die(f"{toml_path.name}: [container].enabled must be a boolean")
    image = container["image"]
    if not isinstance(image, str) or not PINNED_IMAGE_RE.fullmatch(image):
        die(
            f"{toml_path.name}: [container].image must use an immutable "
            "name:tag@sha256 digest"
        )
    for deprecated in ("auto-update", "pull"):
        if deprecated in container:
            die(
                f"{toml_path.name}: [container].{deprecated} is incompatible "
                "with Renovate-managed immutable images"
            )

    if not NAME_RE.match(svc["name"]):
        die(f"{toml_path.name}: [service].name must match {NAME_RE.pattern}")
    if not USERNAME_RE.match(host["username"]):
        die(f"{toml_path.name}: [host].username must match {USERNAME_RE.pattern}")
    krun = cfg.get("krun", {})
    validate_ports(
        toml_path.name,
        container,
        allow_host_network=(
            krun.get("enabled", False) and krun.get("network") == "tap"
        ),
    )
    validate_dns(toml_path.name, container)
    validate_sysctls(toml_path.name, container)
    validate_krun(toml_path.name, cfg)
    if "health-cmd" in container and container["health-cmd"] != "none":
        die(f'{toml_path.name}: [container].health-cmd currently supports only "none"')
    cfg["_toml_path"] = toml_path
    cfg["_slug"] = host["username"].removeprefix("_nas_")
    return cfg


def validate_fleet(configs: list[dict]) -> None:
    seen: dict[str, tuple] = {}
    ranges: list[tuple[int, int, str]] = []
    tap_networks: dict[ipaddress.IPv4Network, str] = {}
    tap_publications: dict[tuple[int, str], str] = {}
    for cfg in configs:
        name = cfg["_toml_path"].name
        for key, value in (
            ("service name", cfg["service"]["name"]),
            ("username", cfg["host"]["username"]),
            ("uid", cfg["host"]["uid"]),
        ):
            if (key, value) in seen:
                die(f"{name}: duplicate {key} {value!r} (also in {seen[(key, value)]})")
            seen[(key, value)] = name
        start = cfg["host"]["subid-start"]
        ranges.append((start, start + SUBID_COUNT, name))
        krun = cfg.get("krun", {})
        if is_active_tap(cfg):
            network = ipaddress.ip_interface(krun["ipv4"]).network
            if network in tap_networks:
                die(f"{name}: TAP subnet {network} is also used by {tap_networks[network]}")
            tap_networks[network] = name
            declared_container_ports = {
                port["container"] for port in cfg["container"].get("ports", [])
            }
            for rule in krun.get("ingress", []):
                unknown_ports = sorted(set(rule["ports"]) - declared_container_ports)
                if unknown_ports:
                    die(
                        f"{name}: TAP ingress ports must also be declared in "
                        f"[[container.ports]]: {', '.join(map(str, unknown_ports))}"
                    )
            for port in cfg["container"].get("ports", []):
                host_port = int(port["host"].rsplit(":", 1)[1])
                key = (host_port, port.get("protocol", "tcp"))
                if key in tap_publications:
                    die(
                        f"{name}: host {key[1]} port {key[0]} is also published "
                        f"by {tap_publications[key]}"
                    )
                tap_publications[key] = name
            if not any(
                port.get("protocol", "tcp") == "tcp"
                for port in cfg["container"].get("ports", [])
            ):
                die(f"{name}: active TAP services need a published TCP probe port")
    ranges.sort()
    for (_, prev_end, prev_name), (cur_start, _, cur_name) in zip(ranges, ranges[1:]):
        if cur_start < prev_end:
            die(f"subordinate ID ranges overlap between {prev_name} and {cur_name}")

    tap_names = {
        cfg["service"]["name"]
        for cfg in configs
        if is_active_tap(cfg)
    }
    for cfg in configs:
        if not is_active_tap(cfg):
            continue
        for rule in cfg["krun"].get("ingress", []):
            source = rule["from"]
            if source not in tap_names:
                die(f"{cfg['_toml_path'].name}: unknown TAP source service {source!r}")


def is_active_tap(cfg: dict) -> bool:
    return cfg["container"].get("enabled", True) and (
        cfg.get("krun", {}).get("network") == "tap"
    )


def active_taps(configs: list[dict]) -> list[dict]:
    return [cfg for cfg in configs if is_active_tap(cfg)]


def tap_name(cfg: dict) -> str:
    name = f"krun-{cfg['host']['uid']}"
    if not TAP_NAME_RE.fullmatch(name):
        die(f"{cfg['_toml_path'].name}: generated invalid TAP name {name!r}")
    return name


def tap_guest(cfg: dict) -> ipaddress.IPv4Interface:
    return ipaddress.ip_interface(cfg["krun"]["ipv4"])


def tap_gateway(cfg: dict) -> ipaddress.IPv4Interface:
    guest = tap_guest(cfg)
    return ipaddress.ip_interface(
        f"{guest.network.network_address + 1}/{guest.network.prefixlen}"
    )


def tap_probe_port(cfg: dict) -> int:
    for port in cfg["container"].get("ports", []):
        if port.get("protocol", "tcp") == "tcp":
            return port["container"]
    die(f"{cfg['_toml_path'].name}: active TAP service has no TCP probe port")


def sops_secret_keys() -> set[str]:
    # SOPS leaves top-level YAML key names in the clear; the only structural
    # key it adds is its own "sops" metadata block.
    keys = set()
    for line in SOPS_FILE.read_text().splitlines():
        m = re.match(r"^([A-Za-z0-9_-]+):", line)
        if m:
            keys.add(m.group(1))
    keys.discard("sops")
    return keys


def verify_sops(configs: list[dict]) -> None:
    declared = {
        (cfg["_toml_path"].name, secret["name"])
        for cfg in configs
        for secret in cfg["container"].get("secrets", [])
    }
    if not declared:
        return
    if not SOPS_FILE.exists():
        die(f"secrets are declared but {SOPS_FILE} does not exist")
    available = sops_secret_keys()
    missing = [(toml, name) for toml, name in sorted(declared) if name not in available]
    if missing:
        for toml, name in missing:
            print(f"ERROR: {toml}: secret {name!r} not found in {SOPS_FILE.name}", file=sys.stderr)
        sys.exit(1)


def container_unit(cfg: dict, configs: list[dict] | None = None) -> str:
    svc, host, container = cfg["service"], cfg["host"], cfg["container"]
    unit = cfg.get("unit", {})
    extra = unit.get("extra", {})
    secrets = container.get("secrets", [])

    lines = [header(cfg["_toml_path"])]
    lines += ["[Unit]", f"Description={svc['description']}"]
    if "documentation" in svc:
        lines.append(f"Documentation={svc['documentation']}")
    lines += extra.get("Unit", [])

    lines += ["", "[Container]"]
    lines.append(f"ContainerName={svc['name']}")
    lines.append(f"Image={container['image']}")
    krun = cfg.get("krun", {})
    if krun.get("enabled", False):
        lines.append("PodmanArgs=--runtime=krun")
        lines.append(f"Annotation=krun.cpus={krun['cpus']}")
        lines.append(f"Annotation=krun.ram_mib={krun['ram-mib']}")
        if krun.get("network", "tsi") == "passt":
            lines.append("Annotation=krun.use_passt=1")
        elif krun.get("network", "tsi") == "tap":
            lines.append(f"Annotation=krun.tap_name={tap_name(cfg)}")
        lines.append("StopSignal=SIGINT")
    if "network" in container:
        lines.append(f"Network={container['network']}")
    if is_active_tap(cfg) and configs is not None:
        # libkrun opens /dev/net/tun after crun enters the container mount
        # namespace, so the device must exist there as well as on the host.
        lines.append("AddDevice=/dev/net/tun")
        for peer in active_taps(configs):
            lines.append(
                f"AddHost={peer['service']['name']}.krun:{tap_guest(peer).ip}"
            )
        lines.append(f"AddHost=host.krun.internal:{tap_gateway(cfg).ip}")
    for server in container.get("dns", []):
        lines.append(f"DNS={server}")
    for setting in container.get("sysctls", []):
        lines.append(f"Sysctl={setting}")
    if "container-user" in container:
        lines.append(f"User={container['container-user']}")
    if "health-cmd" in container:
        lines.append(f"HealthCmd={container['health-cmd']}")

    environment = container.get("environment", {})
    if environment:
        lines.append("")
        lines += [f"Environment={k}={v}" for k, v in environment.items()]

    for volume in container.get("volumes", []):
        lines.append("")
        if "comment" in volume:
            lines.append(f"# {volume['comment']}")
        options = f":{volume['options']}" if volume.get("options") else ""
        lines.append(f"Volume={volume['source']}:{volume['target']}{options}")

    for secret in secrets:
        target = secret.get("target", f"/run/secrets/{secret['name']}")
        lines.append("")
        lines.append("# Runtime secret written at boot by sops-distribute-secrets.service")
        lines.append(f"Volume=/run/nas-secrets/{svc['name']}/{secret['name']}:{target}:ro,Z")

    ports = container.get("ports", [])
    if ports and krun.get("network") != "tap":
        lines.append("")
        for port in ports:
            protocol = port.get("protocol", "tcp")
            suffix = "" if protocol == "tcp" else f"/{protocol}"
            lines.append(f"PublishPort={port['host']}:{port['container']}{suffix}")

    if "exec" in container:
        lines += ["", f"Exec={container['exec']}"]

    lines += extra.get("Container", [])

    lines += ["", "[Service]"]
    if is_active_tap(cfg):
        lines.append(f"ExecStartPre=/usr/bin/test -c /dev/net/tun")
        lines.append(
            "ExecStartPre=/usr/bin/bash -ceu '"
            "for i in {1..90}; do "
            "if /usr/bin/test -r /run/nas-krun-network/policy-ready && "
            f"/usr/bin/test -e /sys/class/net/{tap_name(cfg)}; then exit 0; fi; "
            "sleep 1; done; "
            'echo "krun network policy was not ready within 90 seconds" >&2; exit 1'"'"
        )
    lines += [
        f"ExecStartPre=/usr/bin/test -r /run/nas-secrets/{svc['name']}/{secret['name']}"
        for secret in secrets
    ]
    lines += extra.get("Service", [])
    if is_active_tap(cfg):
        probe_port = tap_probe_port(cfg)
        lines.append(
            "ExecStartPost=/usr/bin/bash -ceu '"
            "for i in {1..30}; do "
            f"if /usr/bin/timeout 1 /usr/bin/bash -c \"</dev/tcp/{tap_guest(cfg).ip}/{probe_port}\" "
            ">/dev/null 2>&1; "
            "then exit 0; fi; sleep 1; done; "
            f"echo \"libkrun guest {tap_guest(cfg).ip}:{probe_port} was not reachable\" >&2; "
            "exit 1'"
        )
    lines.append("Restart=always")
    lines.append(f"RestartSec={unit.get('restart-sec', 30)}")
    if "timeout-start-sec" in unit:
        lines.append(f"TimeoutStartSec={unit['timeout-start-sec']}")

    lines += ["", "[Install]", "WantedBy=default.target"]
    lines += extra.get("Install", [])
    return "\n".join(lines) + "\n"


def sysusers_conf(cfg: dict) -> str:
    host = cfg["host"]
    user, uid, display = host["username"], host["uid"], host["display-name"]
    comment = wrap_comment(
        f"Host account for the rootless {display} Quadlet. This must stay usable by "
        'systemd\'s lingering user manager, so do not mark it as a fully locked "u!" '
        "account."
    )
    return "\n".join(
        [
            header(cfg["_toml_path"]),
            comment,
            f"g {user} {uid}",
            f'u {user} {uid}:{uid} "NAS {display} service user" /var/home/{user} /sbin/nologin',
        ]
    ) + "\n"


def tmpfiles_conf(cfg: dict) -> str:
    host = cfg["host"]
    user, display = host["username"], host["display-name"]
    lines = [
        header(cfg["_toml_path"]),
        wrap_comment(
            f"Rootless {display} uses a namespaced host account so the service identity "
            "does not collide with upstream image defaults."
        ),
    ]
    if "data" in cfg:
        path = cfg["data"]["path"]
        mode = cfg["data"].get("mode", "0750")
        lines.append(f"d {path} {mode} {user} {user} -")
        lines.append(f"Z {path} {mode} {user} {user} -")
    home = f"/var/home/{user}"
    for subdir in ("", "/.config", "/.config/containers", "/.local", "/.local/share",
                   "/.local/share/containers", "/.cache"):
        lines.append(f"d {home}{subdir} 0750 {user} {user} -")
    lines.append("d /var/lib/systemd/linger 0755 root root -")
    lines.append(f"f /var/lib/systemd/linger/{user} 0644 root root -")
    return "\n".join(lines) + "\n"


def ensure_account_script(cfg: dict) -> str:
    host = cfg["host"]
    user, uid = host["username"], host["uid"]

    fcontext_vars = []
    fcontext_calls = []
    if "assets" in cfg:
        fcontext_vars.append(f'ASSETS_FCONTEXT="{cfg["assets"]["path"]}(/.*)?"')
        fcontext_calls.append('ensure_fcontext_rule "${ASSETS_FCONTEXT}"')
    if "data" in cfg:
        fcontext_vars.append(f'DATA_FCONTEXT="{cfg["data"]["path"]}(/.*)?"')
        fcontext_calls.append('ensure_fcontext_rule "${DATA_FCONTEXT}"')

    data_block = ""
    if "data" in cfg:
        data_path = cfg["data"]["path"]
        data_block = f"""
if [[ -e {data_path} ]]; then
    log "Restoring SELinux labels for {data_path}"
    restorecon -F -R {data_path}
fi
"""

    fcontext_var_lines = ("\n" + "\n".join(fcontext_vars)) if fcontext_vars else ""
    fcontext_call_lines = ("\n".join(fcontext_calls) + "\n") if fcontext_calls else ""

    return f"""#!/bin/bash
{header(cfg["_toml_path"])}
# ABOUTME: Ensures the {user} rootless service account has the state
# required for a lingering user manager.

set -euo pipefail

USER_NAME="{user}"
USER_UID="{uid}"
USER_HOME="/var/home/{user}"
USER_SHELL="/sbin/nologin"
USER_SUBID_START="{host["subid-start"]}"
USER_SUBID_COUNT="{SUBID_COUNT}"{fcontext_var_lines}

log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}}

ensure_subid_entry() {{
    local file="$1"
    local expected="${{USER_NAME}}:${{USER_SUBID_START}}:${{USER_SUBID_COUNT}}"
    local current

    if [[ ! -e "${{file}}" ]]; then
        install -o root -g root -m 0644 /dev/null "${{file}}"
    fi

    current="$(grep -E "^${{USER_NAME}}:" "${{file}}" || true)"

    if [[ -z "${{current}}" ]]; then
        log "Adding ${{expected}} to ${{file}}"
        printf '%s\\n' "${{expected}}" >> "${{file}}"
        return
    fi

    if [[ "${{current}}" != "${{expected}}" ]]; then
        log "Leaving existing ${{file}} entry for ${{USER_NAME}}: ${{current}}"
    fi
}}

ensure_fcontext_rule() {{
    local target="$1"

    if semanage fcontext -a -t container_file_t -r s0 "${{target}}" 2>/dev/null; then
        log "Added SELinux fcontext for ${{target}}"
        return
    fi

    semanage fcontext -m -t container_file_t -r s0 "${{target}}"
}}

if ! getent passwd "${{USER_NAME}}" >/dev/null; then
    log "User ${{USER_NAME}} does not exist yet, skipping"
    exit 0
fi

shadow_entry="$(getent shadow "${{USER_NAME}}" || true)"
shadow_password_field="${{shadow_entry#*:}}"
shadow_password_field="${{shadow_password_field%%:*}}"

if [[ -z "${{shadow_password_field}}" || "${{shadow_password_field}}" == "!"* ]]; then
    log "Resetting ${{USER_NAME}} to an invalid but not fully locked password marker"
    usermod --password '*' "${{USER_NAME}}"
fi

log "Clearing account expiry for ${{USER_NAME}}"
chage --expiredate -1 "${{USER_NAME}}"

current_home="$(getent passwd "${{USER_NAME}}" | cut -d: -f6)"
if [[ "${{current_home}}" != "${{USER_HOME}}" ]]; then
    log "Resetting home for ${{USER_NAME}} to ${{USER_HOME}}"
    usermod --home "${{USER_HOME}}" "${{USER_NAME}}"
fi

current_shell="$(getent passwd "${{USER_NAME}}" | cut -d: -f7)"
if [[ "${{current_shell}}" != "${{USER_SHELL}}" ]]; then
    log "Resetting shell for ${{USER_NAME}} to ${{USER_SHELL}}"
    usermod --shell "${{USER_SHELL}}" "${{USER_NAME}}"
fi

ensure_subid_entry /etc/subuid
ensure_subid_entry /etc/subgid
{fcontext_call_lines}{data_block}
if systemctl is-failed --quiet "user@${{USER_UID}}.service"; then
    log "Retrying user@${{USER_UID}}.service after account setup"
    systemctl reset-failed "user@${{USER_UID}}.service"
    systemctl start "user@${{USER_UID}}.service"
fi
"""


def ensure_account_unit(cfg: dict) -> str:
    host = cfg["host"]
    user, uid, slug = host["username"], host["uid"], cfg["_slug"]
    return f"""{header(cfg["_toml_path"])}
[Unit]
Description=Prepare {user} for a lingering user manager
DefaultDependencies=no
After=local-fs.target systemd-sysusers.service systemd-tmpfiles-setup.service
Before=sysinit.target systemd-logind.service user@{uid}.service
ConditionPathExists=/etc/passwd

[Service]
Type=oneshot
ExecStart=/usr/local/bin/ensure-nas-{slug}-account.sh
RemainAfterExit=yes

[Install]
WantedBy=sysinit.target
"""


def networkd_netdev(cfg: dict) -> str:
    host = cfg["host"]
    return f"""{header(cfg['_toml_path'])}
[NetDev]
Name={tap_name(cfg)}
Kind=tap

[Tap]
User={host['username']}
Group={host['username']}
VNetHeader=yes
"""


def networkd_network(cfg: dict) -> str:
    gateway = tap_gateway(cfg)
    return f"""{header(cfg['_toml_path'])}
[Match]
Name={tap_name(cfg)}

[Link]
RequiredForOnline=no

[Network]
Address={gateway}
DHCPServer=yes
ConfigureWithoutCarrier=yes
IPv4RouteLocalnet=yes
LinkLocalAddressing=no
IPv6AcceptRA=no

[DHCPServer]
PoolOffset=2
PoolSize=1
PersistLeases=runtime
RapidCommit=yes
EmitDNS=yes
DNS={' '.join(KRUN_DNS_SERVERS)}
EmitNTP=no
EmitSIP=no
EmitRouter=yes
Router={gateway.ip}
"""


def fleet_header(name: str) -> str:
    return f"{GENERATED_HEADER_PREFIX}{name}{GENERATED_HEADER_SUFFIX}"


def nft_filter(configs: list[dict]) -> str:
    taps = active_taps(configs)
    tap_exclusions = " ".join(f'iifname != "{tap_name(cfg)}"' for cfg in taps)
    out_exclusions = " ".join(f'oifname != "{tap_name(cfg)}"' for cfg in taps)
    by_name = {cfg["service"]["name"]: cfg for cfg in taps}
    lines = [fleet_header("TAP fleet filter"), "chain nas_krun_input {"]
    for cfg in taps:
        lines.append(
            f'    iifname "{tap_name(cfg)}" udp sport 68 udp dport 67 accept'
        )
        lines.append(
            f'    iifname "{tap_name(cfg)}" ip saddr != {tap_guest(cfg).ip} drop'
        )
        lines.append(
            f'    iifname "{tap_name(cfg)}" ip saddr {tap_guest(cfg).ip} '
            "ct state established,related accept"
        )
        for port in cfg["krun"].get("host-access", []):
            lines.append(
                f'    iifname "{tap_name(cfg)}" ip saddr {tap_guest(cfg).ip} '
                f"ip daddr {tap_gateway(cfg).ip} tcp dport {port} accept"
            )
        lines.append(f'    iifname "{tap_name(cfg)}" drop')
    lines += ["}", "", "chain nas_krun_forward {"]
    for cfg in taps:
        lines.append(
            f'    iifname "{tap_name(cfg)}" ip saddr != {tap_guest(cfg).ip} drop'
        )
        lines.append(
            f'    oifname "{tap_name(cfg)}" ip daddr != {tap_guest(cfg).ip} drop'
        )
    lines.append("    ct state established,related accept")
    for destination in taps:
        for rule in destination["krun"].get("ingress", []):
            source = by_name[rule["from"]]
            ports = ", ".join(str(port) for port in rule["ports"])
            lines.append(
                f'    iifname "{tap_name(source)}" oifname "{tap_name(destination)}" '
                f"ip saddr {tap_guest(source).ip} ip daddr {tap_guest(destination).ip} "
                f"tcp dport {{ {ports} }} accept"
            )
    for cfg in taps:
        for port in cfg["container"].get("ports", []):
            address = port["host"].rsplit(":", 1)[0]
            if address != "0.0.0.0":
                continue
            protocol = port.get("protocol", "tcp")
            lines.append(
                f"    {tap_exclusions} oifname \"{tap_name(cfg)}\" "
                f"ip daddr {tap_guest(cfg).ip} {protocol} dport {port['container']} accept"
            )
    for cfg in taps:
        lines.append(
            f'    iifname "{tap_name(cfg)}" ip saddr {tap_guest(cfg).ip} '
            f"{out_exclusions} accept"
        )
    lines += ["}", ""]
    return "\n".join(lines)


def networkd_account_ordering(configs: list[dict]) -> str:
    account_units = [
        f"ensure-nas-{cfg['_slug']}-account.service"
        for cfg in active_taps(configs)
    ]
    return "\n".join(
        [
            fleet_header("networkd TAP account ordering"),
            "[Unit]",
            f"After={' '.join(account_units)}",
            "",
        ]
    )


def network_policy_script(configs: list[dict]) -> str:
    taps = active_taps(configs)
    tap_names = " ".join(f'"{tap_name(cfg)}"' for cfg in taps)
    gateways = " ".join(f'"{tap_gateway(cfg)}"' for cfg in taps)
    user_units = " ".join(f'"user@{cfg["host"]["uid"]}.service"' for cfg in taps)
    wait_interfaces = " ".join(
        f'--interface="{tap_name(cfg)}:off"' for cfg in taps
    )
    return fr"""#!/bin/bash
{fleet_header("TAP network policy readiness")}

set -euo pipefail

READY_DIR=/run/nas-krun-network
READY_FILE="${{READY_DIR}}/policy-ready"
TAPS=({tap_names})
GATEWAYS=({gateways})
USER_UNITS=({user_units})

quiesce_guests() {{
    rm -f "${{READY_FILE}}"
    systemctl stop "${{USER_UNITS[@]}}"
    for unit in "${{USER_UNITS[@]}}"; do
        if systemctl is-active --quiet "${{unit}}"; then
            echo "Refusing to remove krun network policy while ${{unit}} is active" >&2
            return 1
        fi
    done
}}

publish_readiness() {{
    trap 'rm -f "${{READY_FILE}}"' ERR
    install -d -o root -g root -m 0755 "${{READY_DIR}}"
    rm -f "${{READY_FILE}}"

    /usr/lib/systemd/systemd-networkd-wait-online --quiet --timeout=60 \
        --ipv4 {wait_interfaces}

    for index in "${{!TAPS[@]}}"; do
        ip -4 -o address show dev "${{TAPS[$index]}}" \
            | grep -Fq " ${{GATEWAYS[$index]}} "
    done

    nft list chain inet filter nas_krun_input >/dev/null
    nft list chain inet filter nas_krun_forward >/dev/null
    nft list table ip nas_krun_nat >/dev/null

    printf '%s\n' "$(cat /proc/sys/kernel/random/boot_id)" \
        > "${{READY_FILE}}.tmp"
    chown root:root "${{READY_FILE}}.tmp"
    chmod 0644 "${{READY_FILE}}.tmp"
    mv -f "${{READY_FILE}}.tmp" "${{READY_FILE}}"
    systemctl start "${{USER_UNITS[@]}}"
    trap - ERR
}}

case "${{1:-}}" in
    publish)
        publish_readiness
        ;;
    quiesce)
        quiesce_guests
        ;;
    quiesce-and-flush)
        quiesce_guests
        nft flush ruleset
        ;;
    *)
        echo "usage: $0 publish|quiesce|quiesce-and-flush" >&2
        exit 2
        ;;
esac
"""


def network_policy_unit(configs: list[dict]) -> str:
    account_units = [
        f"ensure-nas-{cfg['_slug']}-account.service" for cfg in active_taps(configs)
    ]
    accounts = " ".join(account_units)
    return "\n".join(
        [
            fleet_header("TAP network policy service"),
            "[Unit]",
            "Description=Publish fail-closed readiness for the libkrun TAP network",
            "Requires=nftables.service systemd-networkd.service",
            f"Requires={accounts}",
            "BindsTo=nftables.service systemd-networkd.service",
            "PartOf=nftables.service systemd-networkd.service",
            f"After=nftables.service systemd-networkd.service {accounts}",
            "",
            "[Service]",
            "Type=oneshot",
            "ExecStart=/usr/local/bin/nas-krun-network-policy.sh publish",
            "ExecStop=/usr/local/bin/nas-krun-network-policy.sh quiesce",
            "RemainAfterExit=yes",
            "TimeoutStartSec=90",
            "TimeoutStopSec=180",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )


def nftables_policy_dropin() -> str:
    return "\n".join(
        [
            fleet_header("fail-closed nftables shutdown"),
            "[Service]",
            "ExecStop=",
            "ExecStop=/usr/local/bin/nas-krun-network-policy.sh quiesce-and-flush",
            "",
        ]
    )


def nft_nat(configs: list[dict]) -> str:
    taps = active_taps(configs)
    tap_input_exclusions = " ".join(
        f'iifname != "{tap_name(cfg)}"' for cfg in taps
    )
    tap_output_exclusions = " ".join(
        f'oifname != "{tap_name(cfg)}"' for cfg in taps
    )
    prerouting = []
    output = []
    for cfg in taps:
        guest = tap_guest(cfg).ip
        for port in cfg["container"].get("ports", []):
            address, host_port = port["host"].rsplit(":", 1)
            protocol = port.get("protocol", "tcp")
            destination = f"{guest}:{port['container']}"
            if address == "0.0.0.0":
                prerouting.append(
                    f"        {tap_input_exclusions} fib daddr type local {protocol} "
                    f"dport {host_port} dnat to {destination}"
                )
                output.append(
                    f"        fib daddr type local {protocol} dport {host_port} "
                    f"dnat to {destination}"
                )
            else:
                prerouting.append(
                    f'        iifname "lo" ip daddr {address} {protocol} '
                    f"dport {host_port} dnat to {destination}"
                )
                output.append(
                    f"        ip daddr {address} {protocol} dport {host_port} "
                    f"dnat to {destination}"
                )
    lines = [
        fleet_header("TAP fleet NAT"),
        "table ip nas_krun_nat {",
        "    chain prerouting {",
        "        type nat hook prerouting priority dstnat; policy accept;",
        *prerouting,
        "    }",
        "",
        "    chain output {",
        "        type nat hook output priority dstnat; policy accept;",
        *output,
        "    }",
        "",
        "    chain postrouting {",
        "        type nat hook postrouting priority srcnat; policy accept;",
    ]
    for cfg in taps:
        if cfg["container"].get("ports"):
            lines.append(
                f'        oifname "{tap_name(cfg)}" ip saddr 127.0.0.0/8 '
                f"ip daddr {tap_guest(cfg).ip} snat to {tap_gateway(cfg).ip}"
            )
    for cfg in taps:
        lines.append(
            f"        ip saddr {tap_guest(cfg).ip} {tap_output_exclusions} masquerade"
        )
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def subid_file(configs: list[dict]) -> str:
    # No header comment: shadow-utils does not document comment support in
    # subuid/subgid, so these files stay bare.
    return "".join(
        f"{cfg['host']['username']}:{cfg['host']['subid-start']}:{SUBID_COUNT}\n"
        for cfg in configs
    )


def write(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    changed = not path.exists() or path.read_text() != content
    if changed:
        path.write_text(content)
    if executable:
        path.chmod(0o755)
    print(f"{'wrote' if changed else 'ok   '} {path.relative_to(REPO)}")


def generated_paths(cfg: dict) -> set[Path]:
    uid, slug, name = cfg["host"]["uid"], cfg["_slug"], cfg["service"]["name"]
    paths = {
        OVERLAY / f"usr/lib/sysusers.d/nas-{slug}.conf",
        OVERLAY / f"usr/lib/tmpfiles.d/nas-{slug}-rootless.conf",
        OVERLAY / f"usr/local/bin/ensure-nas-{slug}-account.sh",
        OVERLAY / f"etc/systemd/system/ensure-nas-{slug}-account.service",
    }
    if cfg["container"].get("enabled", True):
        paths.add(OVERLAY / f"etc/containers/systemd/users/{uid}/{name}.container")
    if is_active_tap(cfg):
        paths.add(OVERLAY / f"usr/lib/systemd/network/80-{tap_name(cfg)}.netdev")
        paths.add(OVERLAY / f"usr/lib/systemd/network/80-{tap_name(cfg)}.network")
    return paths


def has_generated_header(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    try:
        with path.open(errors="replace") as generated_file:
            for _ in range(2):
                line = generated_file.readline().rstrip("\n")
                if line.startswith(GENERATED_HEADER_PREFIX) and line.endswith(
                    GENERATED_HEADER_SUFFIX
                ):
                    return True
    except OSError:
        return False
    return False


def remove_stale_generated(expected_paths: set[Path], overlay: Path = OVERLAY) -> None:
    stale_paths = sorted(
        path
        for path in overlay.rglob("*")
        if path not in expected_paths and has_generated_header(path)
    )
    for path in stale_paths:
        path.unlink()
        print(f"removed {path.relative_to(REPO)}")

        # Per-UID Quadlet directories are generator-created. Other output
        # directories are shared with hand-written overlay files.
        users_dir = overlay / "etc/containers/systemd/users"
        if path.parent.parent == users_dir:
            try:
                path.parent.rmdir()
            except OSError:
                pass


def main() -> None:
    toml_paths = sorted(QUADLET_DIR.glob("*.toml"))
    if not toml_paths:
        die(f"no TOML configs found in {QUADLET_DIR}")

    configs = sorted((load_service(p) for p in toml_paths), key=lambda c: c["host"]["uid"])
    validate_fleet(configs)
    verify_sops(configs)

    expected_paths = set()
    fleet_paths = {
        OVERLAY / "etc/nftables/nas-krun-filter.nft",
        OVERLAY / "etc/nftables/nas-krun-nat.nft",
        OVERLAY / "usr/local/bin/nas-krun-network-policy.sh",
        OVERLAY / "etc/systemd/system/nas-krun-network-policy.service",
        OVERLAY / "etc/systemd/system/nftables.service.d/10-nas-krun-policy.conf",
        OVERLAY
        / "etc/systemd/system/systemd-networkd.service.d/10-nas-krun-accounts.conf",
    }
    expected_paths.update(fleet_paths)
    for cfg in configs:
        uid, slug, name = cfg["host"]["uid"], cfg["_slug"], cfg["service"]["name"]
        expected_paths.update(generated_paths(cfg))
        if cfg["container"].get("enabled", True):
            write(
                OVERLAY / f"etc/containers/systemd/users/{uid}/{name}.container",
                container_unit(cfg, configs),
            )
        else:
            print(f"skip  quadlets/{cfg['_toml_path'].name} container (disabled)")
        write(OVERLAY / f"usr/lib/sysusers.d/nas-{slug}.conf", sysusers_conf(cfg))
        write(OVERLAY / f"usr/lib/tmpfiles.d/nas-{slug}-rootless.conf", tmpfiles_conf(cfg))
        write(
            OVERLAY / f"usr/local/bin/ensure-nas-{slug}-account.sh",
            ensure_account_script(cfg),
            executable=True,
        )
        write(
            OVERLAY / f"etc/systemd/system/ensure-nas-{slug}-account.service",
            ensure_account_unit(cfg),
        )
        if is_active_tap(cfg):
            write(
                OVERLAY / f"usr/lib/systemd/network/80-{tap_name(cfg)}.netdev",
                networkd_netdev(cfg),
            )
            write(
                OVERLAY / f"usr/lib/systemd/network/80-{tap_name(cfg)}.network",
                networkd_network(cfg),
            )

    write(OVERLAY / "etc/subuid", subid_file(configs))
    write(OVERLAY / "etc/subgid", subid_file(configs))
    write(
        OVERLAY / "usr/local/bin/nas-krun-network-policy.sh",
        network_policy_script(configs),
        executable=True,
    )
    write(
        OVERLAY / "etc/systemd/system/nas-krun-network-policy.service",
        network_policy_unit(configs),
    )
    write(
        OVERLAY / "etc/systemd/system/nftables.service.d/10-nas-krun-policy.conf",
        nftables_policy_dropin(),
    )
    write(
        OVERLAY
        / "etc/systemd/system/systemd-networkd.service.d/10-nas-krun-accounts.conf",
        networkd_account_ordering(configs),
    )
    write(OVERLAY / "etc/nftables/nas-krun-filter.nft", nft_filter(configs))
    write(OVERLAY / "etc/nftables/nas-krun-nat.nft", nft_nat(configs))
    remove_stale_generated(expected_paths)


if __name__ == "__main__":
    main()
