# ABOUTME: Shared fixtures for the rootless-service compiler tests.

from __future__ import annotations

from pathlib import Path

from quadletgen.model import Fleet
from quadletgen.parser import load_service


REPO = Path(__file__).resolve().parents[1]
OVERLAY = REPO / "overlay-root"
GENERATED_PREFIX = "# GENERATED by generate-quadlets.py from quadlets/"


def current_fleet() -> Fleet:
    return Fleet.build(
        [load_service(path) for path in (REPO / "quadlets").glob("*.toml")]
    )


def service_toml(
    *,
    name: str = "service",
    uid: int = 51999,
    subid_start: int = 519990000,
    application: str | None = None,
    role: str = "test",
    container: str = "",
    krun: str | None = None,
    extra: str = "",
) -> str:
    krun_section = f"\n[krun]\n{krun}\n" if krun is not None else ""
    return f"""
[service]
name = "{name}"
application = "{application or name}"
role = "{role}"
description = "Test service"

[host]
username = "_nas_{name.replace('-', '')}"
uid = {uid}
subid-start = {subid_start}
display-name = "Test service"

[container]
image = "example.invalid/{name}:1@sha256:{'a' * 64}"
{container}
{krun_section}
{extra}
"""
