# ABOUTME: Tests the typed rootless-service compiler and artifact synchronization.

from __future__ import annotations

import contextlib
import io
import stat
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path

from quadletgen.compiler import Artifact, compile_fleet
from quadletgen.model import ConfigError, DataSpec, Fleet, KrunNetwork, Protocol
from quadletgen.parser import load_service
from quadletgen.sync import sync_artifacts


REPO = Path(__file__).resolve().parents[1]
OVERLAY = REPO / "overlay-root"
GENERATED_PREFIX = "# GENERATED by generate-quadlets.py from quadlets/"


def current_fleet() -> Fleet:
    return Fleet.build(
        [load_service(path) for path in (REPO / "quadlets").glob("*.toml")]
    )


def service_toml(
    *,
    name: str = "service",
    uid: int = 51999,
    subid_start: int = 519990000,
    container: str = "",
    krun: str | None = None,
    extra: str = "",
) -> str:
    krun_section = f"\n[krun]\n{krun}\n" if krun is not None else ""
    return f"""
[service]
name = "{name}"
description = "Test service"

[host]
username = "_nas_{name.replace('-', '')}"
uid = {uid}
subid-start = {subid_start}
display-name = "Test service"

[container]
image = "example.invalid/{name}:1@sha256:{'a' * 64}"
{container}
{krun_section}
{extra}
"""


class CompilerCharacterizationTests(unittest.TestCase):
    def test_compiler_exactly_reproduces_every_tracked_generated_artifact(self):
        artifacts = compile_fleet(current_fleet())
        compiled_paths = {artifact.path for artifact in artifacts}

        tracked_generated = set()
        for path in OVERLAY.rglob("*"):
            if not path.is_file() or path.is_symlink():
                continue
            first_two = path.read_text(errors="replace").splitlines()[:2]
            if any(line.startswith(GENERATED_PREFIX) for line in first_two):
                tracked_generated.add(path.relative_to(OVERLAY))
        tracked_generated.update({Path("etc/subuid"), Path("etc/subgid")})

        self.assertEqual(compiled_paths, tracked_generated)
        for artifact in artifacts:
            with self.subTest(path=artifact.path):
                path = OVERLAY / artifact.path
                self.assertEqual(artifact.content, path.read_text())
                executable = bool(path.stat().st_mode & stat.S_IXUSR)
                self.assertEqual(artifact.executable, executable)

    def test_current_fleet_is_typed_and_uid_ordered(self):
        fleet = current_fleet()

        self.assertEqual(len(fleet.services), 9)
        self.assertEqual(len(fleet.active_taps), 9)
        self.assertEqual(
            [service.host.uid for service in fleet.services],
            sorted(service.host.uid for service in fleet.services),
        )
        self.assertTrue(
            all(
                service.krun is not None
                and service.krun.network is KrunNetwork.TAP
                for service in fleet.active_taps
            )
        )


class FleetManifestTests(unittest.TestCase):
    def setUp(self):
        self.fleet = current_fleet()
        self.artifacts = {
            artifact.path: artifact.content
            for artifact in compile_fleet(self.fleet)
        }

    def rows(self, path: str):
        return [
            line.split("\t")
            for line in self.artifacts[Path(path)].splitlines()
            if line and not line.startswith("#")
        ]

    def test_manifests_encode_account_and_active_tap_membership(self):
        account_units = [
            line
            for line in self.artifacts[
                Path("usr/share/custom-coreos/fleet/account-units.list")
            ].splitlines()
            if line and not line.startswith("#")
        ]
        tap_rows = self.rows("usr/share/custom-coreos/fleet/active-taps.tsv")

        self.assertEqual(
            account_units,
            sorted(
                f"ensure-nas-{service.host.slug}-account.service"
                for service in self.fleet.services
            ),
        )
        self.assertEqual(
            tap_rows,
            [
                [
                    service.tap_name,
                    f"user@{service.host.uid}.service",
                    f"ensure-nas-{service.host.slug}-account.service",
                ]
                for service in self.fleet.active_taps
            ],
        )

    def test_secret_and_asset_manifests_are_derived_from_typed_fields(self):
        secret_rows = self.rows("usr/share/custom-coreos/fleet/secrets.tsv")
        asset_rows = [
            [line]
            for line in self.artifacts[
                Path("usr/share/custom-coreos/fleet/assets.list")
            ].splitlines()
            if line and not line.startswith("#")
        ]

        expected_secrets = [
            [service.info.name, service.host.username, secret.name]
            for service in sorted(
                self.fleet.services,
                key=lambda item: item.source.name,
            )
            for secret in service.container.secrets
        ]
        expected_assets = [
            [service.assets.path]
            for service in sorted(
                self.fleet.services,
                key=lambda item: item.assets.path if item.assets else "",
            )
            if service.assets is not None
        ]
        self.assertEqual(secret_rows, expected_secrets)
        self.assertEqual(asset_rows, expected_assets)

    def test_non_python_consumers_no_longer_parse_or_duplicate_the_fleet(self):
        containerfile = (REPO / "Containerfile").read_text()
        distributor = (
            OVERLAY / "usr/local/bin/sops-distribute-secrets.sh"
        ).read_text()
        diagnostics = (
            REPO / "scripts/collect-krun-network-diagnostics.sh"
        ).read_text()

        self.assertNotIn("COPY quadlets/", containerfile)
        self.assertIn("fleet/account-units.list", containerfile)
        self.assertIn("fleet/assets.list", containerfile)
        self.assertNotIn("ensure-nas-alertmanager-account.service \\", containerfile)
        self.assertIn("fleet/secrets.tsv", distributor)
        self.assertNotIn("read_quadlet_secret_rows", distributor)
        self.assertNotIn("QUADLET_DIR", distributor)
        self.assertIn("fleet/active-taps.tsv", diagnostics)
        self.assertNotIn("krun-51110 krun-51120", diagnostics)

    def test_selinux_labeling_has_one_owner_per_storage_class(self):
        containerfile = (REPO / "Containerfile").read_text()
        self.assertIn('awk "NF && !/^#/"', containerfile)
        self.assertIn('restorecon -F -R -- "${asset}"', containerfile)
        self.assertNotIn('restorecon -F -R "${image_assets[@]}"', containerfile)
        self.assertNotIn('/var/lib/grafana(/.*)?', containerfile)

        for service in self.fleet.services:
            script = self.artifacts[
                Path(
                    f"usr/local/bin/ensure-nas-{service.host.slug}-account.sh"
                )
            ]
            if service.assets is not None:
                self.assertNotIn(service.assets.path, script)
            if service.data is None:
                self.assertNotIn("semanage fcontext", script)
                self.assertNotIn("restorecon", script)
            else:
                self.assertIn(service.data.path, script)
                self.assertIn("semanage fcontext", script)
                self.assertIn("restorecon", script)

    def test_runtime_data_path_is_escaped_for_selinux_regex(self):
        changed = self.fleet.services[0]
        changed = replace(
            changed,
            data=DataSpec("/var/lib/service.v2"),
        )
        fleet = Fleet.build(
            [
                changed if service.info.name == changed.info.name else service
                for service in self.fleet.services
            ]
        )
        artifacts = {
            artifact.path: artifact.content
            for artifact in compile_fleet(fleet)
        }
        script = artifacts[
            Path(
                f"usr/local/bin/ensure-nas-{changed.host.slug}-account.sh"
            )
        ]
        self.assertIn(
            'DATA_FCONTEXT="/var/lib/service\\.v2(/.*)?"',
            script,
        )


class StartupPolicyTests(unittest.TestCase):
    def setUp(self):
        self.artifacts = {
            artifact.path: artifact.content
            for artifact in compile_fleet(current_fleet())
        }

    def test_current_services_use_typed_startup_policy_only(self):
        for toml_path in (REPO / "quadlets").glob("*.toml"):
            self.assertNotIn("[unit.extra]", toml_path.read_text())

        garage = self.artifacts[
            Path("etc/containers/systemd/users/51110/garage.container")
        ]
        jellyfin = self.artifacts[
            Path("etc/containers/systemd/users/51120/jellyfin.container")
        ]
        vmalert = self.artifacts[
            Path("etc/containers/systemd/users/51220/vmalert.container")
        ]
        self.assertIn(
            "nas-wait-for-readiness.sh marker /run/garage-datasets/ready "
            "3600 2 /var/lib/garage/meta=tank/garage/meta "
            "/var/lib/garage/data=tank/garage/data",
            garage,
        )
        self.assertIn(
            "nas-assert-tcp-ports-free.sh 3900 3902 3903",
            garage,
        )
        self.assertIn(
            "/var/zfs/tank/videos=tank/videos",
            jellyfin,
        )
        self.assertIn(
            "nas-wait-for-readiness.sh http "
            "http://127.0.0.1:8428/-/healthy 300 2",
            vmalert,
        )
        for artifact in self.artifacts.values():
            self.assertNotIn("ExecStartPre=/usr/bin/bash -lc", artifact)

    def test_data_subdirectories_are_owned_by_tmpfiles(self):
        tmpfiles = self.artifacts[
            Path("usr/lib/tmpfiles.d/nas-alertmanager-rootless.conf")
        ]
        child = (
            "d /var/lib/alertmanager/data 0750 "
            "_nas_alertmanager _nas_alertmanager -"
        )
        recursive_label = (
            "Z /var/lib/alertmanager 0750 "
            "_nas_alertmanager _nas_alertmanager -"
        )
        self.assertIn(child, tmpfiles)
        self.assertLess(tmpfiles.index(child), tmpfiles.index(recursive_label))
        alertmanager = self.artifacts[
            Path("etc/containers/systemd/users/51240/alertmanager.container")
        ]
        self.assertNotIn("install -d", alertmanager)


class StrictParserTests(unittest.TestCase):
    def load(self, source: str, filename: str = "service.toml"):
        with tempfile.TemporaryDirectory(dir=REPO) as directory:
            path = Path(directory) / filename
            path.write_text(source)
            return load_service(path)

    def assert_invalid(self, source: str, message: str) -> None:
        with self.assertRaisesRegex(ConfigError, message):
            self.load(source)

    def assert_invalid_field(self, source: str, field: str) -> None:
        with self.assertRaises(ConfigError) as raised:
            self.load(source)
        self.assertIn(field, str(raised.exception))

    def test_rejects_unknown_keys_at_every_closed_boundary(self):
        self.assert_invalid(
            service_toml(extra="\n[typo]\nvalue = true"),
            "unknown keys: typo",
        )
        self.assert_invalid(
            service_toml(container="imag = \"typo\""),
            "unknown keys: imag",
        )
        self.assert_invalid(
            service_toml(
                krun=(
                    "enabled = true\ncpus = 1\nram-mib = 128\n"
                    "network-mode = \"tap\""
                )
            ),
            "unknown keys: network-mode",
        )

    def test_requires_immutable_image_reference(self):
        self.assert_invalid(
            service_toml().replace(
                f"example.invalid/service:1@sha256:{'a' * 64}",
                "example.invalid/service:1",
            ),
            "immutable name:tag@sha256 digest",
        )

    def test_service_identity_matches_dns_and_source_filename_contracts(self):
        for invalid_name in ("service-", "s" * 64):
            with self.subTest(name=invalid_name):
                self.assert_invalid(
                    service_toml().replace(
                        'name = "service"',
                        f'name = "{invalid_name}"',
                    ),
                    "must match",
                )

        with self.assertRaisesRegex(ConfigError, "filename must be"):
            self.load(service_toml(), filename="different.toml")

    def test_host_identity_stays_inside_repository_allocators(self):
        too_long_username = "_nas_" + "s" * 27
        self.assert_invalid_field(
            service_toml().replace(
                'username = "_nas_service"',
                f'username = "{too_long_username}"',
            ),
            "[host].username",
        )
        self.assert_invalid(
            service_toml(uid=50999),
            "must be at least 51000",
        )
        self.assert_invalid(
            service_toml(subid_start=2**32),
            "must be at most",
        )
        self.assert_invalid_field(
            service_toml().replace(
                'display-name = "Test service"',
                'display-name = "Test:service"',
            ),
            "[host].display-name",
        )

    def test_parses_typed_ports_dns_sysctls_and_secrets_in_source_order(self):
        service = self.load(
            service_toml(
                container="""
dns = ["100.100.100.100", "2001:db8::53"]
sysctls = ["net.ipv4.ip_forward=1"]

[[container.ports]]
host = "127.0.0.1:8080"
container = 80

[[container.ports]]
host = "[0:0:0:0:0:0:0:1]:5353"
container = 5353
protocol = "udp"

[[container.secrets]]
name = "token"
"""
            )
        )

        self.assertEqual(
            [port.protocol for port in service.container.ports],
            [Protocol.TCP, Protocol.UDP],
        )
        self.assertEqual(
            [str(server) for server in service.container.dns],
            ["100.100.100.100", "2001:db8::53"],
        )
        self.assertEqual(service.container.ports[1].host, "[::1]:5353")
        self.assertEqual(service.container.sysctls, ("net.ipv4.ip_forward=1",))
        self.assertEqual(service.container.secrets[0].name, "token")

    def test_rejects_invalid_port_declarations(self):
        cases = {
            "hostname": 'host = "localhost:8080"\ncontainer = 80',
            "unbracketed IPv6": 'host = "::1:8080"\ncontainer = 80',
            "port zero": 'host = "127.0.0.1:0"\ncontainer = 80',
            "boolean": 'host = "127.0.0.1:8080"\ncontainer = true',
            "protocol": (
                'host = "127.0.0.1:8080"\ncontainer = 80\n'
                'protocol = "sctp"'
            ),
        }
        for label, declaration in cases.items():
            with self.subTest(label=label):
                self.assert_invalid(
                    service_toml(
                        container=f"\n[[container.ports]]\n{declaration}"
                    ),
                    "container",
                )

    def test_enum_type_errors_remain_configuration_errors(self):
        self.assert_invalid_field(
            service_toml(
                container=(
                    "[[container.ports]]\n"
                    'host = "127.0.0.1:8080"\n'
                    "container = 80\n"
                    'protocol = ["tcp"]'
                )
            ),
            "[container].ports[1].protocol",
        )
        self.assert_invalid_field(
            service_toml(
                krun=(
                    "enabled = true\ncpus = 1\nram-mib = 128\n"
                    'network = ["tap"]'
                )
            ),
            "[krun].network",
        )

    def test_duplicate_ports_use_typed_canonical_endpoints(self):
        self.assert_invalid(
            service_toml(
                container=(
                    "[[container.ports]]\n"
                    'host = "[::1]:5353"\n'
                    "container = 5353\n"
                    'protocol = "udp"\n\n'
                    "[[container.ports]]\n"
                    'host = "[0:0:0:0:0:0:0:1]:5353"\n'
                    "container = 5354\n"
                    'protocol = "udp"'
                )
            ),
            "duplicate published port",
        )

    def test_rejects_host_ports_without_tap_exception(self):
        self.assert_invalid(
            service_toml(
                container=(
                    'network = "host"\n\n[[container.ports]]\n'
                    'host = "127.0.0.1:8080"\ncontainer = 80'
                )
            ),
            "cannot be used with network",
        )

    def test_rejects_invalid_krun_variants(self):
        cases = {
            "missing enabled": "cpus = 1\nram-mib = 128",
            "disabled fields": "enabled = false\ncpus = 1",
            "low RAM": "enabled = true\ncpus = 1\nram-mib = 127",
            "passt host": (
                "enabled = true\ncpus = 1\nram-mib = 128\n"
                'network = "passt"'
            ),
        }
        for label, krun in cases.items():
            with self.subTest(label=label):
                container = 'network = "host"' if label == "passt host" else ""
                self.assert_invalid(
                    service_toml(container=container, krun=krun),
                    "krun",
                )

    def test_disabled_krun_normalizes_to_absence(self):
        self.assertIsNone(self.load(service_toml(krun="enabled = false")).krun)

    def test_tap_uses_explicit_probe_port_and_derives_network_values(self):
        service = self.load(
            service_toml(
                container=(
                    'network = "host"\n\n[[container.ports]]\n'
                    'host = "127.0.0.1:8081"\ncontainer = 8081\n\n'
                    '[[container.ports]]\n'
                    'host = "127.0.0.1:8080"\ncontainer = 8080'
                ),
                krun=(
                    "enabled = true\ncpus = 1\nram-mib = 128\n"
                    'network = "tap"\nipv4 = "10.253.99.2/30"\n'
                    "probe-port = 8080"
                ),
            )
        )

        self.assertTrue(service.active_tap)
        self.assertEqual(service.tap_name, "krun-51999")
        self.assertEqual(str(service.tap_guest), "10.253.99.2/30")
        self.assertEqual(str(service.tap_gateway), "10.253.99.1/30")
        self.assertEqual(service.tap_spec.probe_port, 8080)
        artifacts = {
            artifact.path: artifact.content
            for artifact in compile_fleet(Fleet.build([service]))
        }
        unit = artifacts[
            Path("etc/containers/systemd/users/51999/service.container")
        ]
        self.assertIn("/dev/tcp/10.253.99.2/8080", unit)
        self.assertNotIn("/dev/tcp/10.253.99.2/8081", unit)

    def test_tap_probe_must_reference_a_declared_tcp_container_port(self):
        container = (
            'network = "host"\n\n[[container.ports]]\n'
            'host = "127.0.0.1:8080"\ncontainer = 8080\n'
            'protocol = "udp"'
        )
        base_krun = (
            "enabled = true\ncpus = 1\nram-mib = 128\n"
            'network = "tap"\nipv4 = "10.253.99.2/30"'
        )

        self.assert_invalid(
            service_toml(container=container, krun=base_krun),
            "missing 'probe-port'",
        )
        self.assert_invalid(
            service_toml(
                container=container,
                krun=f"{base_krun}\nprobe-port = 8080",
            ),
            "declared TCP container port",
        )

    def test_health_cmd_supports_only_explicit_disable(self):
        service = self.load(service_toml(container='health-cmd = "none"'))
        self.assertEqual(service.container.health_cmd, "none")
        self.assert_invalid(
            service_toml(container='health-cmd = "curl /health"'),
            "supports only",
        )

    def test_single_line_fields_reject_directive_injection(self):
        cases = {
            "[service].description": service_toml().replace(
                'description = "Test service"',
                'description = "Test service\\nRequires=evil.service"',
            ),
            "[service].documentation": service_toml().replace(
                'description = "Test service"',
                'description = "Test service"\n'
                'documentation = "https://example.invalid/\\nRequires=evil.service"',
            ),
            "[host].display-name": service_toml().replace(
                'display-name = "Test service"',
                'display-name = "Test service\\nZ /tmp 0777 root root -"',
            ),
            "[container].exec": service_toml(
                container='exec = "server\\nEnvironment=EVIL=1"'
            ),
            "[container].volumes[1].comment": service_toml(
                container=(
                    "[[container.volumes]]\n"
                    'source = "/var/lib/service"\n'
                    'target = "/data"\n'
                    'comment = "safe\\nVolume=/tmp:/escape"'
                )
            ),
        }
        for field, source in cases.items():
            with self.subTest(field=field):
                self.assert_invalid_field(source, field)

    def test_unit_atoms_reject_ambiguous_systemd_syntax(self):
        cases = {
            "[container].image": service_toml().replace(
                "example.invalid/service:1@sha256:",
                "example.invalid/%service:1@sha256:",
            ),
            "[container.environment].BAD": service_toml(
                container='[container.environment]\nBAD = "two words"'
            ),
            "[container.environment].DOLLAR": service_toml(
                container=(
                    "[container.environment]\n"
                    'DOLLAR = "${USER}"'
                )
            ),
            "[container].sysctls": service_toml(
                container='sysctls = ["net.ipv4.ip_forward=%n"]'
            ),
            "[container].exec": service_toml(container='exec = "server; reboot"'),
            "[startup.readiness].url": service_toml(
                extra=(
                    "[startup.readiness]\n"
                    'url = "http://127.0.0.1:bad/ready"\n'
                    "timeout-sec = 5\ninterval-sec = 1"
                )
            ),
        }
        for field, source in cases.items():
            with self.subTest(field=field):
                self.assert_invalid_field(source, field)
        self.assert_invalid_field(
            service_toml(
                extra=(
                    "[startup.readiness]\n"
                    'url = "http://${HOST}:8080/ready"\n'
                    "timeout-sec = 5\ninterval-sec = 1"
                )
            ),
            "[startup.readiness].url",
        )

    def test_environment_names_are_identifiers(self):
        for environment_name in ("BAD-NAME", "1BAD"):
            with self.subTest(name=environment_name):
                self.assert_invalid_field(
                    service_toml(
                        container=(
                            "[container.environment]\n"
                            f'"{environment_name}" = "value"'
                        )
                    ),
                    "[container.environment] key",
                )

    def test_paths_and_modes_match_their_output_grammars(self):
        cases = {
            "[container].volumes[1].source": service_toml(
                container=(
                    "[[container.volumes]]\n"
                    'source = "/var/lib/../escape"\n'
                    'target = "/data"'
                )
            ),
            "[container].volumes[1].target": service_toml(
                container=(
                    "[[container.volumes]]\n"
                    'source = "/var/lib/service"\n'
                    'target = "/data:other"'
                )
            ),
            "[container].volumes[1].options": service_toml(
                container=(
                    "[[container.volumes]]\n"
                    'source = "/var/lib/service"\n'
                    'target = "/data"\n'
                    'options = "ro;rw"'
                )
            ),
            "[container].secrets[1].target": service_toml(
                container=(
                    "[[container.secrets]]\n"
                    'name = "token"\n'
                    'target = "relative/path"'
                )
            ),
            "[data].path": service_toml(
                extra='[data]\npath = "/tmp/service"'
            ),
            "[data].mode": service_toml(
                extra=(
                    "[data]\n"
                    'path = "/var/lib/service"\n'
                    'mode = "0888"'
                )
            ),
            "[assets].path": service_toml(
                extra=(
                    "[assets]\n"
                    'path = "/usr/share/custom-coreos/somewhere-else"'
                )
            ),
            "[startup.readiness].marker": service_toml(
                extra=(
                    "[startup.readiness]\n"
                    'marker = "/run/service/../ready"\n'
                    "timeout-sec = 5\ninterval-sec = 1"
                )
            ),
            "[[startup.readiness.mounts]][1].source": service_toml(
                extra=(
                    "[startup.readiness]\n"
                    'marker = "/run/service/ready"\n'
                    "timeout-sec = 5\ninterval-sec = 1\n\n"
                    "[[startup.readiness.mounts]]\n"
                    'path = "/var/lib/service"\n'
                    'source = "tank/service;bad"'
                )
            ),
        }
        for field, source in cases.items():
            with self.subTest(field=field):
                self.assert_invalid_field(source, field)

    def test_manifest_fields_reject_delimiters(self):
        self.assert_invalid(
            service_toml(
                container=(
                    "[[container.secrets]]\n"
                    'name = "bad\\tname"'
                )
            ),
            "control characters",
        )
        self.assert_invalid(
            service_toml(
                extra=(
                    "[assets]\n"
                    'path = "/usr/share/bad\\npath"'
                )
            ),
            "control characters",
        )

    def test_startup_policy_rejects_ambiguous_or_persistent_readiness(self):
        cases = {
            "both targets": (
                "[startup.readiness]\n"
                'marker = "/run/service/ready"\n'
                'url = "http://127.0.0.1/ready"\n'
                "timeout-sec = 5\ninterval-sec = 1"
            ),
            "persistent marker": (
                "[startup.readiness]\n"
                'marker = "/var/lib/service/ready"\n'
                "timeout-sec = 5\ninterval-sec = 1"
            ),
            "missing interval": (
                "[startup.readiness]\n"
                'marker = "/run/service/ready"\n'
                "timeout-sec = 5"
            ),
            "URL without host": (
                "[startup.readiness]\n"
                'url = "http:///ready"\n'
                "timeout-sec = 5\ninterval-sec = 1"
            ),
        }
        for label, startup in cases.items():
            with self.subTest(label=label):
                self.assert_invalid(service_toml(extra=startup), "startup.readiness")

    def test_startup_port_guard_and_subdirectories_are_validated(self):
        self.assert_invalid(
            service_toml(
                extra=(
                    "[startup]\n"
                    "reject-published-tcp-ports = true"
                )
            ),
            "requires at least one published TCP port",
        )
        self.assert_invalid(
            service_toml(
                extra=(
                    "[data]\n"
                    'path = "/var/lib/service"\n'
                    'subdirectories = ["../escape"]'
                )
            ),
            "unsafe relative path",
        )


class FleetValidationTests(unittest.TestCase):
    def write(self, directory: Path, filename: str, source: str):
        path = directory / filename
        path.write_text(source)
        return load_service(path)

    def test_rejects_duplicate_identity_and_overlapping_subids(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            first = self.write(
                directory,
                "first.toml",
                service_toml(name="first", uid=51991, subid_start=600000000),
            )
            duplicate_uid = self.write(
                directory,
                "second.toml",
                service_toml(name="second", uid=51991, subid_start=700000000),
            )
            with self.assertRaisesRegex(ConfigError, "duplicate uid"):
                Fleet.build([first, duplicate_uid])

            overlapping = self.write(
                directory,
                "third.toml",
                service_toml(name="third", uid=51992, subid_start=600000001),
            )
            with self.assertRaisesRegex(ConfigError, "ranges overlap"):
                Fleet.build([first, overlapping])

    def test_rejects_host_port_collisions_for_non_tap_publishers(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            first = self.write(
                directory,
                "first.toml",
                service_toml(
                    name="first",
                    uid=51970,
                    subid_start=600000000,
                    container=(
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:8080"\n'
                        "container = 8080"
                    ),
                ),
            )
            second = self.write(
                directory,
                "second.toml",
                service_toml(
                    name="second",
                    uid=51980,
                    subid_start=700000000,
                    container=(
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:8080"\n'
                        "container = 8080"
                    ),
                ),
            )
            tap = self.write(
                directory,
                "tap.toml",
                service_toml(
                    name="tap",
                    uid=51990,
                    subid_start=800000000,
                    container=(
                        'network = "host"\n\n'
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:9090"\n'
                        "container = 9090"
                    ),
                    krun=(
                        "enabled = true\ncpus = 1\nram-mib = 128\n"
                        'network = "tap"\n'
                        'ipv4 = "10.253.99.2/30"\n'
                        "probe-port = 9090"
                    ),
                ),
            )

            with self.assertRaisesRegex(
                ConfigError,
                "host tcp port 8080 is also published by first.toml",
            ):
                Fleet.build([first, second, tap])

    def test_disabled_service_keeps_identity_but_has_no_runtime_artifacts(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            disabled = self.write(
                directory,
                "disabled.toml",
                service_toml(
                    name="disabled",
                    container=(
                        "enabled = false\n"
                        'network = "host"\n\n'
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:8080"\n'
                        "container = 8080\n\n"
                        "[[container.secrets]]\n"
                        'name = "disabled-token"'
                    ),
                    krun=(
                        "enabled = true\ncpus = 1\nram-mib = 128\n"
                        'network = "tap"\n'
                        'ipv4 = "10.253.99.2/30"\n'
                        "probe-port = 8080"
                    ),
                    extra=(
                        "\n[assets]\n"
                        'path = "/usr/share/custom-coreos/disabled"'
                    ),
                ),
            )
            active = self.write(
                directory,
                "active.toml",
                service_toml(
                    name="active",
                    uid=51990,
                    subid_start=800000000,
                    container=(
                        'network = "host"\n\n'
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:8080"\n'
                        "container = 8080"
                    ),
                    krun=(
                        "enabled = true\ncpus = 1\nram-mib = 128\n"
                        'network = "tap"\n'
                        'ipv4 = "10.253.98.2/30"\n'
                        "probe-port = 8080"
                    ),
                ),
            )
            fleet = Fleet.build([disabled, active])
            artifacts = {
                artifact.path: artifact.content
                for artifact in compile_fleet(fleet)
            }
            paths = set(artifacts)

        self.assertIn(Path("usr/lib/sysusers.d/nas-disabled.conf"), paths)
        self.assertIn(Path("etc/subuid"), paths)
        self.assertNotIn(
            Path("etc/containers/systemd/users/51999/disabled.container"),
            paths,
        )
        self.assertEqual(
            [service.info.name for service in fleet.active_taps],
            ["active"],
        )
        self.assertIn(
            "ensure-nas-disabled-account.service",
            artifacts[Path("usr/share/custom-coreos/fleet/account-units.list")],
        )
        self.assertNotIn(
            "krun-51999\t",
            artifacts[Path("usr/share/custom-coreos/fleet/active-taps.tsv")],
        )
        self.assertIn(
            "disabled\t_nas_disabled\tdisabled-token",
            artifacts[Path("usr/share/custom-coreos/fleet/secrets.tsv")],
        )
        self.assertIn(
            "/usr/share/custom-coreos/disabled",
            artifacts[Path("usr/share/custom-coreos/fleet/assets.list")],
        )

    def test_fleet_requires_at_least_one_active_tap(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            service = self.write(
                directory,
                "service.toml",
                service_toml(),
            )
            with self.assertRaisesRegex(
                ConfigError,
                "must contain at least one active TAP service",
            ):
                Fleet.build([service])

    def test_active_fleet_without_assets_emits_a_header_only_manifest(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            service = self.write(
                directory,
                "service.toml",
                service_toml(
                    container=(
                        'network = "host"\n\n'
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:8080"\n'
                        "container = 8080"
                    ),
                    krun=(
                        "enabled = true\ncpus = 1\nram-mib = 128\n"
                        'network = "tap"\n'
                        'ipv4 = "10.253.99.2/30"\n'
                        "probe-port = 8080"
                    ),
                ),
            )
            artifacts = {
                artifact.path: artifact.content
                for artifact in compile_fleet(Fleet.build([service]))
            }

        assets = artifacts[
            Path("usr/share/custom-coreos/fleet/assets.list")
        ]
        self.assertEqual(
            [line for line in assets.splitlines() if not line.startswith("#")],
            [],
        )
        account_script = artifacts[
            Path("usr/local/bin/ensure-nas-service-account.sh")
        ]
        self.assertNotIn("semanage fcontext", account_script)
        self.assertNotIn("restorecon", account_script)


class ArtifactSynchronizationTests(unittest.TestCase):
    def test_sync_removes_only_stale_generated_files(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            repo = Path(directory_name)
            overlay = repo / "overlay-root"
            stale = overlay / "etc/containers/systemd/users/59999/old.container"
            handwritten = overlay / "etc/systemd/system/handwritten.service"
            stale.parent.mkdir(parents=True)
            handwritten.parent.mkdir(parents=True)
            stale.write_text(
                GENERATED_PREFIX + "old.toml — DO NOT EDIT\n"
            )
            handwritten.write_text("[Unit]\nDescription=Handwritten\n")
            artifact = Artifact(
                Path("etc/systemd/system/current.service"),
                GENERATED_PREFIX + "current.toml — DO NOT EDIT\n",
            )

            with contextlib.redirect_stdout(io.StringIO()):
                sync_artifacts(repo, overlay, (artifact,))

            self.assertFalse(stale.exists())
            self.assertFalse(stale.parent.exists())
            self.assertTrue(handwritten.exists())
            self.assertEqual(
                (overlay / artifact.path).read_text(), artifact.content
            )

    def test_sync_does_not_follow_generated_symlink(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            repo = Path(directory_name)
            overlay = repo / "overlay-root"
            target = repo / "target"
            link = overlay / "usr/local/bin/link"
            link.parent.mkdir(parents=True)
            target.write_text(GENERATED_PREFIX + "old.toml — DO NOT EDIT\n")
            link.symlink_to(target)

            with contextlib.redirect_stdout(io.StringIO()):
                sync_artifacts(repo, overlay, ())

            self.assertTrue(link.is_symlink())
            self.assertTrue(target.exists())


if __name__ == "__main__":
    unittest.main()
