# ABOUTME: Verifies container mounts and readiness are derived from storage policy.

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from quadletgen.parser import load_service
from quadletgen.render_service import container_unit
from quadletgen.render_storage import (
    storage_manifest,
    storage_readiness_line,
    storage_unit,
)
from tests.quadlet_test_support import REPO, current_fleet, service_toml


STORAGE = """
[[storage]]
name = "state"
kind = "directory"
host-path = "/var/lib/service"
mode = "0750"
subdirectories = ["data"]

[[storage.exports]]
subpath = "data"
container-path = "/data"
access = "read-write"

[[storage]]
name = "media"
kind = "existing-zfs"
dataset = "tank/videos"
host-path = "/var/zfs/tank/videos"

[[storage.exports]]
subpath = "movies"
container-path = "/media/movies"
access = "read-only"
"""


class StorageRenderingTests(unittest.TestCase):
    def load(self, extra: str):
        with tempfile.TemporaryDirectory(dir=REPO) as directory:
            path = Path(directory) / "service.toml"
            path.write_text(service_toml(extra=extra))
            return load_service(path)

    def test_mounts_and_current_boot_readiness_share_one_source(self):
        service = self.load(STORAGE)
        unit = container_unit(service, current_fleet())

        self.assertIn("Volume=/var/lib/service/data:/data", unit)
        self.assertIn(
            "Volume=/var/zfs/tank/videos/movies:/media/movies:ro",
            unit,
        )
        self.assertIn(
            "marker /run/nas-storage/service/ready 300 2",
            unit,
        )
        self.assertIn("TimeoutStartSec=330", unit)
        self.assertIn(
            "--path /var/lib/service/data --owner 51999:51999 "
            "--access rwx",
            unit,
        )
        self.assertIn(
            "--path /var/zfs/tank/videos/movies --source tank/videos "
            "--access rx",
            unit,
        )

    def test_storage_and_dependency_readiness_are_composable(self):
        service = self.load(
            STORAGE
            + """
[[startup.dependencies]]
service = "database"
endpoint = "postgres"
condition = "tcp"
timeout-sec = 30
interval-sec = 1
"""
        )

        self.assertEqual(len(service.startup.dependencies), 1)
        self.assertIsNotNone(storage_readiness_line(service))

    def test_host_manifest_and_unit_are_generated_from_the_same_contract(self):
        service = self.load(STORAGE)
        manifest = storage_manifest(service)
        unit = storage_unit(service)

        self.assertEqual(
            manifest.splitlines(),
            [
                "nas-storage-manifest-v3",
                "# GENERATED by generate-quadlets.py from "
                "quadlets/service.toml — DO NOT EDIT",
                "service|service|_nas_service|51999|51999|519990000|65536|-|-",
                "directory|/var/lib/service|0750",
                "directory|/var/lib/service/data|0750",
                "existing-zfs|tank/videos|/var/zfs/tank/videos",
            ],
        )
        self.assertIn("Requires=zfs.target ensure-nas-service-account.service", unit)
        self.assertIn("ConditionPathIsDirectory=/sys/module/zfs", unit)
        self.assertIn(
            "ExecStart=/usr/local/bin/nas-prepare-storage.sh "
            "/usr/share/nas/storage/service.storage-manifest",
            unit,
        )
        self.assertIn("RestartPreventExitStatus=78", unit)


if __name__ == "__main__":
    unittest.main()
