# ABOUTME: Tests the typed rootless-service compiler and artifact synchronization.

from __future__ import annotations

import contextlib
import io
import stat
import tempfile
import unittest
from pathlib import Path

from quadletgen.compiler import Artifact, compile_fleet
from quadletgen.model import ConfigError, Fleet, KrunNetwork, Protocol
from quadletgen.parser import load_service
from quadletgen.sync import sync_artifacts


REPO = Path(__file__).resolve().parents[1]
OVERLAY = REPO / "overlay-root"
GENERATED_PREFIX = "# GENERATED by generate-quadlets.py from quadlets/"


def current_fleet() -> Fleet:
    return Fleet.build(
        [load_service(path) for path in (REPO / "quadlets").glob("*.toml")]
    )


def service_toml(
    *,
    name: str = "service",
    uid: int = 51999,
    subid_start: int = 519990000,
    container: str = "",
    krun: str | None = None,
    extra: str = "",
) -> str:
    krun_section = f"\n[krun]\n{krun}\n" if krun is not None else ""
    return f"""
[service]
name = "{name}"
description = "Test service"

[host]
username = "_nas_{name.replace('-', '')}"
uid = {uid}
subid-start = {subid_start}
display-name = "Test service"

[container]
image = "example.invalid/{name}:1@sha256:{'a' * 64}"
{container}
{krun_section}
{extra}
"""


class CompilerCharacterizationTests(unittest.TestCase):
    def test_compiler_exactly_reproduces_every_tracked_generated_artifact(self):
        artifacts = compile_fleet(current_fleet())
        compiled_paths = {artifact.path for artifact in artifacts}

        tracked_generated = set()
        for path in OVERLAY.rglob("*"):
            if not path.is_file() or path.is_symlink():
                continue
            first_two = path.read_text(errors="replace").splitlines()[:2]
            if any(line.startswith(GENERATED_PREFIX) for line in first_two):
                tracked_generated.add(path.relative_to(OVERLAY))
        tracked_generated.update({Path("etc/subuid"), Path("etc/subgid")})

        self.assertEqual(compiled_paths, tracked_generated)
        for artifact in artifacts:
            with self.subTest(path=artifact.path):
                path = OVERLAY / artifact.path
                self.assertEqual(artifact.content, path.read_text())
                executable = bool(path.stat().st_mode & stat.S_IXUSR)
                self.assertEqual(artifact.executable, executable)

    def test_current_fleet_is_typed_and_uid_ordered(self):
        fleet = current_fleet()

        self.assertEqual(len(fleet.services), 9)
        self.assertEqual(len(fleet.active_taps), 9)
        self.assertEqual(
            [service.host.uid for service in fleet.services],
            sorted(service.host.uid for service in fleet.services),
        )
        self.assertTrue(
            all(
                service.krun is not None
                and service.krun.network is KrunNetwork.TAP
                for service in fleet.active_taps
            )
        )


class FleetManifestTests(unittest.TestCase):
    def setUp(self):
        self.fleet = current_fleet()
        self.artifacts = {
            artifact.path: artifact.content
            for artifact in compile_fleet(self.fleet)
        }

    def rows(self, path: str):
        return [
            line.split("\t")
            for line in self.artifacts[Path(path)].splitlines()
            if line and not line.startswith("#")
        ]

    def test_manifests_encode_account_and_active_tap_membership(self):
        account_units = [
            line
            for line in self.artifacts[
                Path("usr/share/custom-coreos/fleet/account-units.list")
            ].splitlines()
            if line and not line.startswith("#")
        ]
        tap_rows = self.rows("usr/share/custom-coreos/fleet/active-taps.tsv")

        self.assertEqual(
            account_units,
            sorted(
                f"ensure-nas-{service.host.slug}-account.service"
                for service in self.fleet.services
            ),
        )
        self.assertEqual(
            tap_rows,
            [
                [
                    service.tap_name,
                    f"user@{service.host.uid}.service",
                    f"ensure-nas-{service.host.slug}-account.service",
                ]
                for service in self.fleet.active_taps
            ],
        )

    def test_secret_and_asset_manifests_are_derived_from_typed_fields(self):
        secret_rows = self.rows("usr/share/custom-coreos/fleet/secrets.tsv")
        asset_rows = [
            [line]
            for line in self.artifacts[
                Path("usr/share/custom-coreos/fleet/assets.list")
            ].splitlines()
            if line and not line.startswith("#")
        ]

        expected_secrets = [
            [service.info.name, service.host.username, secret.name]
            for service in sorted(
                self.fleet.services,
                key=lambda item: item.source.name,
            )
            for secret in service.container.secrets
        ]
        expected_assets = [
            [service.assets.path]
            for service in sorted(
                self.fleet.services,
                key=lambda item: item.assets.path if item.assets else "",
            )
            if service.assets is not None
        ]
        self.assertEqual(secret_rows, expected_secrets)
        self.assertEqual(asset_rows, expected_assets)

    def test_non_python_consumers_no_longer_parse_or_duplicate_the_fleet(self):
        containerfile = (REPO / "Containerfile").read_text()
        distributor = (
            OVERLAY / "usr/local/bin/sops-distribute-secrets.sh"
        ).read_text()
        diagnostics = (
            REPO / "scripts/collect-krun-network-diagnostics.sh"
        ).read_text()

        self.assertNotIn("COPY quadlets/", containerfile)
        self.assertIn("fleet/account-units.list", containerfile)
        self.assertIn("fleet/assets.list", containerfile)
        self.assertNotIn("ensure-nas-alertmanager-account.service \\", containerfile)
        self.assertIn("fleet/secrets.tsv", distributor)
        self.assertNotIn("read_quadlet_secret_rows", distributor)
        self.assertNotIn("QUADLET_DIR", distributor)
        self.assertIn("fleet/active-taps.tsv", diagnostics)
        self.assertNotIn("krun-51110 krun-51120", diagnostics)


class StrictParserTests(unittest.TestCase):
    def load(self, source: str):
        with tempfile.TemporaryDirectory(dir=REPO) as directory:
            path = Path(directory) / "service.toml"
            path.write_text(source)
            return load_service(path)

    def assert_invalid(self, source: str, message: str) -> None:
        with self.assertRaisesRegex(ConfigError, message):
            self.load(source)

    def test_rejects_unknown_keys_at_every_closed_boundary(self):
        self.assert_invalid(
            service_toml(extra="\n[typo]\nvalue = true"),
            "unknown keys: typo",
        )
        self.assert_invalid(
            service_toml(container="imag = \"typo\""),
            "unknown keys: imag",
        )
        self.assert_invalid(
            service_toml(
                krun=(
                    "enabled = true\ncpus = 1\nram-mib = 128\n"
                    "network-mode = \"tap\""
                )
            ),
            "unknown keys: network-mode",
        )

    def test_requires_immutable_image_reference(self):
        self.assert_invalid(
            service_toml().replace(
                f"example.invalid/service:1@sha256:{'a' * 64}",
                "example.invalid/service:1",
            ),
            "immutable name:tag@sha256 digest",
        )

    def test_parses_typed_ports_dns_sysctls_and_secrets_in_source_order(self):
        service = self.load(
            service_toml(
                container="""
dns = ["100.100.100.100", "2001:db8::53"]
sysctls = ["net.ipv4.ip_forward=1"]

[[container.ports]]
host = "127.0.0.1:8080"
container = 80

[[container.ports]]
host = "[::1]:5353"
container = 5353
protocol = "udp"

[[container.secrets]]
name = "token"
"""
            )
        )

        self.assertEqual(
            [port.protocol for port in service.container.ports],
            [Protocol.TCP, Protocol.UDP],
        )
        self.assertEqual(
            [str(server) for server in service.container.dns],
            ["100.100.100.100", "2001:db8::53"],
        )
        self.assertEqual(service.container.sysctls, ("net.ipv4.ip_forward=1",))
        self.assertEqual(service.container.secrets[0].name, "token")

    def test_rejects_invalid_port_declarations(self):
        cases = {
            "hostname": 'host = "localhost:8080"\ncontainer = 80',
            "unbracketed IPv6": 'host = "::1:8080"\ncontainer = 80',
            "port zero": 'host = "127.0.0.1:0"\ncontainer = 80',
            "boolean": 'host = "127.0.0.1:8080"\ncontainer = true',
            "protocol": (
                'host = "127.0.0.1:8080"\ncontainer = 80\n'
                'protocol = "sctp"'
            ),
        }
        for label, declaration in cases.items():
            with self.subTest(label=label):
                self.assert_invalid(
                    service_toml(
                        container=f"\n[[container.ports]]\n{declaration}"
                    ),
                    "container",
                )

    def test_rejects_host_ports_without_tap_exception(self):
        self.assert_invalid(
            service_toml(
                container=(
                    'network = "host"\n\n[[container.ports]]\n'
                    'host = "127.0.0.1:8080"\ncontainer = 80'
                )
            ),
            "cannot be used with network",
        )

    def test_rejects_invalid_krun_variants(self):
        cases = {
            "missing enabled": "cpus = 1\nram-mib = 128",
            "disabled fields": "enabled = false\ncpus = 1",
            "low RAM": "enabled = true\ncpus = 1\nram-mib = 127",
            "passt host": (
                "enabled = true\ncpus = 1\nram-mib = 128\n"
                'network = "passt"'
            ),
        }
        for label, krun in cases.items():
            with self.subTest(label=label):
                container = 'network = "host"' if label == "passt host" else ""
                self.assert_invalid(
                    service_toml(container=container, krun=krun),
                    "krun",
                )

    def test_tap_derives_network_values_once_in_model(self):
        service = self.load(
            service_toml(
                container=(
                    'network = "host"\n\n[[container.ports]]\n'
                    'host = "127.0.0.1:8080"\ncontainer = 8080'
                ),
                krun=(
                    "enabled = true\ncpus = 1\nram-mib = 128\n"
                    'network = "tap"\nipv4 = "10.253.99.2/30"'
                ),
            )
        )

        self.assertTrue(service.active_tap)
        self.assertEqual(service.tap_name, "krun-51999")
        self.assertEqual(str(service.tap_guest), "10.253.99.2/30")
        self.assertEqual(str(service.tap_gateway), "10.253.99.1/30")
        self.assertEqual(service.tap_probe_port, 8080)

    def test_health_cmd_supports_only_explicit_disable(self):
        service = self.load(service_toml(container='health-cmd = "none"'))
        self.assertEqual(service.container.health_cmd, "none")
        self.assert_invalid(
            service_toml(container='health-cmd = "curl /health"'),
            "supports only",
        )

    def test_manifest_fields_reject_delimiters(self):
        self.assert_invalid(
            service_toml(
                container=(
                    "[[container.secrets]]\n"
                    'name = "bad\\tname"'
                )
            ),
            "must match",
        )
        self.assert_invalid(
            service_toml(
                extra=(
                    "[assets]\n"
                    'path = "/usr/share/bad\\npath"'
                )
            ),
            "tabs or newlines",
        )


class FleetValidationTests(unittest.TestCase):
    def write(self, directory: Path, filename: str, source: str):
        path = directory / filename
        path.write_text(source)
        return load_service(path)

    def test_rejects_duplicate_identity_and_overlapping_subids(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            first = self.write(
                directory,
                "first.toml",
                service_toml(name="first", uid=51991, subid_start=600000000),
            )
            duplicate_uid = self.write(
                directory,
                "second.toml",
                service_toml(name="second", uid=51991, subid_start=700000000),
            )
            with self.assertRaisesRegex(ConfigError, "duplicate uid"):
                Fleet.build([first, duplicate_uid])

            overlapping = self.write(
                directory,
                "third.toml",
                service_toml(name="third", uid=51992, subid_start=600000001),
            )
            with self.assertRaisesRegex(ConfigError, "ranges overlap"):
                Fleet.build([first, overlapping])

    def test_disabled_service_keeps_identity_but_has_no_runtime_artifacts(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            directory = Path(directory_name)
            disabled = self.write(
                directory,
                "disabled.toml",
                service_toml(
                    name="disabled",
                    container=(
                        "enabled = false\n"
                        'network = "host"\n\n'
                        "[[container.ports]]\n"
                        'host = "127.0.0.1:8080"\n'
                        "container = 8080\n\n"
                        "[[container.secrets]]\n"
                        'name = "disabled-token"'
                    ),
                    krun=(
                        "enabled = true\ncpus = 1\nram-mib = 128\n"
                        'network = "tap"\n'
                        'ipv4 = "10.253.99.2/30"'
                    ),
                    extra=(
                        "\n[assets]\n"
                        'path = "/usr/share/custom-coreos/disabled"'
                    ),
                ),
            )
            fleet = Fleet.build([disabled])
            artifacts = {
                artifact.path: artifact.content
                for artifact in compile_fleet(fleet)
            }
            paths = set(artifacts)

        self.assertIn(Path("usr/lib/sysusers.d/nas-disabled.conf"), paths)
        self.assertIn(Path("etc/subuid"), paths)
        self.assertNotIn(
            Path("etc/containers/systemd/users/51999/disabled.container"),
            paths,
        )
        self.assertFalse(fleet.active_taps)
        self.assertIn(
            "ensure-nas-disabled-account.service",
            artifacts[Path("usr/share/custom-coreos/fleet/account-units.list")],
        )
        self.assertNotIn(
            "krun-51999\t",
            artifacts[Path("usr/share/custom-coreos/fleet/active-taps.tsv")],
        )
        self.assertIn(
            "disabled\t_nas_disabled\tdisabled-token",
            artifacts[Path("usr/share/custom-coreos/fleet/secrets.tsv")],
        )
        self.assertIn(
            "/usr/share/custom-coreos/disabled",
            artifacts[Path("usr/share/custom-coreos/fleet/assets.list")],
        )


class ArtifactSynchronizationTests(unittest.TestCase):
    def test_sync_removes_only_stale_generated_files(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            repo = Path(directory_name)
            overlay = repo / "overlay-root"
            stale = overlay / "etc/containers/systemd/users/59999/old.container"
            handwritten = overlay / "etc/systemd/system/handwritten.service"
            stale.parent.mkdir(parents=True)
            handwritten.parent.mkdir(parents=True)
            stale.write_text(
                GENERATED_PREFIX + "old.toml — DO NOT EDIT\n"
            )
            handwritten.write_text("[Unit]\nDescription=Handwritten\n")
            artifact = Artifact(
                Path("etc/systemd/system/current.service"),
                GENERATED_PREFIX + "current.toml — DO NOT EDIT\n",
            )

            with contextlib.redirect_stdout(io.StringIO()):
                sync_artifacts(repo, overlay, (artifact,))

            self.assertFalse(stale.exists())
            self.assertFalse(stale.parent.exists())
            self.assertTrue(handwritten.exists())
            self.assertEqual(
                (overlay / artifact.path).read_text(), artifact.content
            )

    def test_sync_does_not_follow_generated_symlink(self):
        with tempfile.TemporaryDirectory(dir=REPO) as directory_name:
            repo = Path(directory_name)
            overlay = repo / "overlay-root"
            target = repo / "target"
            link = overlay / "usr/local/bin/link"
            link.parent.mkdir(parents=True)
            target.write_text(GENERATED_PREFIX + "old.toml — DO NOT EDIT\n")
            link.symlink_to(target)

            with contextlib.redirect_stdout(io.StringIO()):
                sync_artifacts(repo, overlay, ())

            self.assertTrue(link.is_symlink())
            self.assertTrue(target.exists())


if __name__ == "__main__":
    unittest.main()
