[secrets]
driver = "shell"

[secrets.opts]
list = "/usr/local/lib/podman-secret-driver/list.sh"
lookup = "/usr/local/lib/podman-secret-driver/lookup.sh"
store = "/usr/local/lib/podman-secret-driver/store.sh"
delete = "/usr/local/lib/podman-secret-driver/delete.sh"
